# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_semiautomaticclassificationplugin_dock_class.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DockClass(object):
    def setupUi(self, DockClass):
        DockClass.setObjectName("DockClass")
        DockClass.resize(397, 496)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DockClass.sizePolicy().hasHeightForWidth())
        DockClass.setSizePolicy(sizePolicy)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tabWidget_dock = QtWidgets.QTabWidget(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_dock.sizePolicy().hasHeightForWidth())
        self.tabWidget_dock.setSizePolicy(sizePolicy)
        self.tabWidget_dock.setStyleSheet("QTabBar::tab {padding-bottom: 2px; padding-top: 2px;margin-bottom: 0px; margin-top: 0px; padding-left: 1ex;padding-right: 0.8ex;}")
        self.tabWidget_dock.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget_dock.setIconSize(QtCore.QSize(15, 15))
        self.tabWidget_dock.setDocumentMode(True)
        self.tabWidget_dock.setObjectName("tabWidget_dock")
        self.tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab.sizePolicy().hasHeightForWidth())
        self.tab.setSizePolicy(sizePolicy)
        self.tab.setObjectName("tab")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_40 = QtWidgets.QGridLayout()
        self.gridLayout_40.setHorizontalSpacing(8)
        self.gridLayout_40.setObjectName("gridLayout_40")
        self.batch_toolButton = QtWidgets.QToolButton(self.tab)
        self.batch_toolButton.setStyleSheet("margin: 0px;padding: 0px;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_batch.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.batch_toolButton.setIcon(icon)
        self.batch_toolButton.setIconSize(QtCore.QSize(22, 22))
        self.batch_toolButton.setObjectName("batch_toolButton")
        self.gridLayout_40.addWidget(self.batch_toolButton, 0, 9, 1, 1)
        self.postprocessing_toolButton_2 = QtWidgets.QToolButton(self.tab)
        self.postprocessing_toolButton_2.setStyleSheet("margin: 0px;padding: 0px;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_post_process.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.postprocessing_toolButton_2.setIcon(icon1)
        self.postprocessing_toolButton_2.setIconSize(QtCore.QSize(22, 22))
        self.postprocessing_toolButton_2.setObjectName("postprocessing_toolButton_2")
        self.gridLayout_40.addWidget(self.postprocessing_toolButton_2, 0, 7, 1, 1)
        self.preprocessing_toolButton_2 = QtWidgets.QToolButton(self.tab)
        self.preprocessing_toolButton_2.setStyleSheet("margin: 0px;padding: 0px;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_class_tool.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.preprocessing_toolButton_2.setIcon(icon2)
        self.preprocessing_toolButton_2.setIconSize(QtCore.QSize(22, 22))
        self.preprocessing_toolButton_2.setObjectName("preprocessing_toolButton_2")
        self.gridLayout_40.addWidget(self.preprocessing_toolButton_2, 0, 5, 1, 1)
        self.bandset_toolButton = QtWidgets.QToolButton(self.tab)
        self.bandset_toolButton.setStyleSheet("margin: 0px;padding: 0px;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_bandset_tool.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bandset_toolButton.setIcon(icon3)
        self.bandset_toolButton.setIconSize(QtCore.QSize(22, 22))
        self.bandset_toolButton.setObjectName("bandset_toolButton")
        self.gridLayout_40.addWidget(self.bandset_toolButton, 0, 0, 1, 1)
        self.bandcalc_toolButton_2 = QtWidgets.QToolButton(self.tab)
        self.bandcalc_toolButton_2.setStyleSheet("margin: 0px;padding: 0px;")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_bandcalc_tool.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bandcalc_toolButton_2.setIcon(icon4)
        self.bandcalc_toolButton_2.setIconSize(QtCore.QSize(22, 22))
        self.bandcalc_toolButton_2.setObjectName("bandcalc_toolButton_2")
        self.gridLayout_40.addWidget(self.bandcalc_toolButton_2, 0, 8, 1, 1)
        self.download_images_toolButton_2 = QtWidgets.QToolButton(self.tab)
        self.download_images_toolButton_2.setStyleSheet("margin: 0px;padding: 0px;")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_download_arrow.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.download_images_toolButton_2.setIcon(icon5)
        self.download_images_toolButton_2.setIconSize(QtCore.QSize(22, 22))
        self.download_images_toolButton_2.setObjectName("download_images_toolButton_2")
        self.gridLayout_40.addWidget(self.download_images_toolButton_2, 0, 2, 1, 1)
        self.band_processing_toolButton = QtWidgets.QToolButton(self.tab)
        self.band_processing_toolButton.setStyleSheet("margin: 0px;padding: 0px;")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_band_processing.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.band_processing_toolButton.setIcon(icon6)
        self.band_processing_toolButton.setIconSize(QtCore.QSize(22, 22))
        self.band_processing_toolButton.setObjectName("band_processing_toolButton")
        self.gridLayout_40.addWidget(self.band_processing_toolButton, 0, 6, 1, 1)
        self.basic_tools_toolButton = QtWidgets.QToolButton(self.tab)
        self.basic_tools_toolButton.setStyleSheet("margin: 0px;padding: 0px;")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_roi_tool.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.basic_tools_toolButton.setIcon(icon7)
        self.basic_tools_toolButton.setIconSize(QtCore.QSize(22, 22))
        self.basic_tools_toolButton.setObjectName("basic_tools_toolButton")
        self.gridLayout_40.addWidget(self.basic_tools_toolButton, 0, 1, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_40, 1, 0, 1, 1)
        self.plugin_version_label2 = QtWidgets.QLabel(self.tab)
        self.plugin_version_label2.setText("")
        self.plugin_version_label2.setAlignment(QtCore.Qt.AlignCenter)
        self.plugin_version_label2.setObjectName("plugin_version_label2")
        self.gridLayout_11.addWidget(self.plugin_version_label2, 0, 0, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_11, 0, 1, 1, 1)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_35 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("background-color : #656565; color : white; font: bold;")
        self.label_35.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_35.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_35.setObjectName("label_35")
        self.gridLayout_12.addWidget(self.label_35, 0, 0, 1, 1)
        self.main_textBrowser = QtWidgets.QTextBrowser(self.tab)
        self.main_textBrowser.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'DejaVu Sans\'; font-size:9pt;\"><br /></span></p></body></html>")
        self.main_textBrowser.setOpenExternalLinks(True)
        self.main_textBrowser.setObjectName("main_textBrowser")
        self.gridLayout_12.addWidget(self.main_textBrowser, 1, 0, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_12, 1, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.userguide_toolButton_2 = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.userguide_toolButton_2.setFont(font)
        self.userguide_toolButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.userguide_toolButton_2.setStyleSheet("color: white;\n"
"background-color: rgb(51, 122, 183);\n"
"selection-color: yellow;\n"
"selection-background-color: blue;\n"
"font: bold 14px;\n"
"border-style: inset;\n"
"border-width: 2px;\n"
"border-radius: 6px;\n"
"border-color: white;\n"
"padding: 2px;")
        self.userguide_toolButton_2.setObjectName("userguide_toolButton_2")
        self.verticalLayout.addWidget(self.userguide_toolButton_2)
        self.help_toolButton_2 = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.help_toolButton_2.setFont(font)
        self.help_toolButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.help_toolButton_2.setStyleSheet("color: white;\n"
"background-color: rgb(51, 122, 183);\n"
"selection-color: yellow;\n"
"selection-background-color: blue;\n"
"font: bold 14px;\n"
"border-style: inset;\n"
"border-width: 2px;\n"
"border-radius: 6px;\n"
"border-color: white;\n"
"padding: 2px;")
        self.help_toolButton_2.setObjectName("help_toolButton_2")
        self.verticalLayout.addWidget(self.help_toolButton_2)
        self.support_toolButton = QtWidgets.QPushButton(self.tab)
        self.support_toolButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.support_toolButton.setStyleSheet("color: white;\n"
"background-color: rgb(92, 184, 92);\n"
"selection-color: yellow;\n"
"selection-background-color: blue;\n"
"font: bold 14px;\n"
"border-style: inset;\n"
"border-width: 2px;\n"
"border-radius: 6px;\n"
"border-color: white;\n"
"padding: 2px;")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.support_toolButton.setIcon(icon8)
        self.support_toolButton.setFlat(False)
        self.support_toolButton.setObjectName("support_toolButton")
        self.verticalLayout.addWidget(self.support_toolButton)
        self.gridLayout_14.addLayout(self.verticalLayout, 2, 1, 1, 1)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_home.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_dock.addTab(self.tab, icon9, "")
        self.tab_2 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_2.sizePolicy().hasHeightForWidth())
        self.tab_2.setSizePolicy(sizePolicy)
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_19 = QtWidgets.QGridLayout()
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.button_new_input = QtWidgets.QToolButton(self.tab_2)
        self.button_new_input.setStyleSheet("margin: 0px;padding: 0px;")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_new_file.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_new_input.setIcon(icon10)
        self.button_new_input.setIconSize(QtCore.QSize(22, 22))
        self.button_new_input.setObjectName("button_new_input")
        self.gridLayout_19.addWidget(self.button_new_input, 0, 1, 1, 1)
        self.trainingFile_lineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.trainingFile_lineEdit.setEnabled(False)
        self.trainingFile_lineEdit.setObjectName("trainingFile_lineEdit")
        self.gridLayout_19.addWidget(self.trainingFile_lineEdit, 0, 2, 1, 1)
        self.trainingFile_toolButton = QtWidgets.QToolButton(self.tab_2)
        self.trainingFile_toolButton.setStyleSheet("margin: 0px;padding: 0px;")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_open_file.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.trainingFile_toolButton.setIcon(icon11)
        self.trainingFile_toolButton.setIconSize(QtCore.QSize(22, 22))
        self.trainingFile_toolButton.setObjectName("trainingFile_toolButton")
        self.gridLayout_19.addWidget(self.trainingFile_toolButton, 0, 0, 1, 1)
        self.button_reset_input = QtWidgets.QToolButton(self.tab_2)
        self.button_reset_input.setStyleSheet("margin: 0px;padding: 0px;")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_reset.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_reset_input.setIcon(icon12)
        self.button_reset_input.setIconSize(QtCore.QSize(22, 22))
        self.button_reset_input.setObjectName("button_reset_input")
        self.gridLayout_19.addWidget(self.button_reset_input, 0, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_19)
        self.label_48 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setStyleSheet("background-color : #656565; color : white; font: bold;")
        self.label_48.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_48.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_48.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_48.setObjectName("label_48")
        self.verticalLayout_2.addWidget(self.label_48)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.merge_signature_toolButton = QtWidgets.QToolButton(self.tab_2)
        self.merge_signature_toolButton.setStyleSheet("margin: 0px;padding: 0px;")
        self.merge_signature_toolButton.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_merge_sign_tool.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.merge_signature_toolButton.setIcon(icon13)
        self.merge_signature_toolButton.setIconSize(QtCore.QSize(22, 22))
        self.merge_signature_toolButton.setObjectName("merge_signature_toolButton")
        self.verticalLayout_4.addWidget(self.merge_signature_toolButton)
        self.calculate_signature_toolButton = QtWidgets.QToolButton(self.tab_2)
        self.calculate_signature_toolButton.setStyleSheet("margin: 0px;padding: 0px;")
        self.calculate_signature_toolButton.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_add_sign_tool.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.calculate_signature_toolButton.setIcon(icon14)
        self.calculate_signature_toolButton.setIconSize(QtCore.QSize(22, 22))
        self.calculate_signature_toolButton.setObjectName("calculate_signature_toolButton")
        self.verticalLayout_4.addWidget(self.calculate_signature_toolButton)
        self.delete_Signature_Button = QtWidgets.QToolButton(self.tab_2)
        self.delete_Signature_Button.setStyleSheet("margin: 0px;padding: 0px;")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_delete_signature.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_Signature_Button.setIcon(icon15)
        self.delete_Signature_Button.setIconSize(QtCore.QSize(22, 22))
        self.delete_Signature_Button.setObjectName("delete_Signature_Button")
        self.verticalLayout_4.addWidget(self.delete_Signature_Button)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.signature_spectral_plot_toolButton = QtWidgets.QToolButton(self.tab_2)
        self.signature_spectral_plot_toolButton.setStyleSheet("margin: 0px;padding: 0px;")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_sign_tool.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.signature_spectral_plot_toolButton.setIcon(icon16)
        self.signature_spectral_plot_toolButton.setIconSize(QtCore.QSize(22, 22))
        self.signature_spectral_plot_toolButton.setObjectName("signature_spectral_plot_toolButton")
        self.verticalLayout_4.addWidget(self.signature_spectral_plot_toolButton)
        self.scatterPlot_toolButton = QtWidgets.QToolButton(self.tab_2)
        self.scatterPlot_toolButton.setStyleSheet("margin: 0px;padding: 0px;")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_scatter_tool.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.scatterPlot_toolButton.setIcon(icon17)
        self.scatterPlot_toolButton.setIconSize(QtCore.QSize(22, 22))
        self.scatterPlot_toolButton.setObjectName("scatterPlot_toolButton")
        self.verticalLayout_4.addWidget(self.scatterPlot_toolButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.import_library_toolButton = QtWidgets.QToolButton(self.tab_2)
        self.import_library_toolButton.setStyleSheet("margin: 0px;padding: 0px;")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_import_spectral_library.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.import_library_toolButton.setIcon(icon18)
        self.import_library_toolButton.setIconSize(QtCore.QSize(22, 22))
        self.import_library_toolButton.setObjectName("import_library_toolButton")
        self.verticalLayout_4.addWidget(self.import_library_toolButton)
        self.export_signature_list_toolButton = QtWidgets.QToolButton(self.tab_2)
        self.export_signature_list_toolButton.setStyleSheet("margin: 0px;padding: 0px;")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_export_spectral_library.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.export_signature_list_toolButton.setIcon(icon19)
        self.export_signature_list_toolButton.setIconSize(QtCore.QSize(22, 22))
        self.export_signature_list_toolButton.setObjectName("export_signature_list_toolButton")
        self.verticalLayout_4.addWidget(self.export_signature_list_toolButton)
        self.gridLayout.addLayout(self.verticalLayout_4, 1, 0, 1, 1)
        self.ROI_filter_lineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.ROI_filter_lineEdit.setObjectName("ROI_filter_lineEdit")
        self.gridLayout.addWidget(self.ROI_filter_lineEdit, 0, 0, 1, 2)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.gridLayout_27 = QtWidgets.QGridLayout()
        self.gridLayout_27.setVerticalSpacing(4)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.label_41 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_41.sizePolicy().hasHeightForWidth())
        self.label_41.setSizePolicy(sizePolicy)
        self.label_41.setObjectName("label_41")
        self.gridLayout_27.addWidget(self.label_41, 1, 3, 1, 1)
        self.ROI_Macroclass_ID_spin = QtWidgets.QSpinBox(self.tab_2)
        self.ROI_Macroclass_ID_spin.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ROI_Macroclass_ID_spin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ROI_Macroclass_ID_spin.setMinimum(0)
        self.ROI_Macroclass_ID_spin.setMaximum(9999)
        self.ROI_Macroclass_ID_spin.setProperty("value", 1)
        self.ROI_Macroclass_ID_spin.setObjectName("ROI_Macroclass_ID_spin")
        self.gridLayout_27.addWidget(self.ROI_Macroclass_ID_spin, 0, 1, 1, 2)
        self.label_42 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_42.sizePolicy().hasHeightForWidth())
        self.label_42.setSizePolicy(sizePolicy)
        self.label_42.setMaximumSize(QtCore.QSize(89, 16777215))
        self.label_42.setObjectName("label_42")
        self.gridLayout_27.addWidget(self.label_42, 1, 0, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_45.sizePolicy().hasHeightForWidth())
        self.label_45.setSizePolicy(sizePolicy)
        self.label_45.setObjectName("label_45")
        self.gridLayout_27.addWidget(self.label_45, 0, 3, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_44.sizePolicy().hasHeightForWidth())
        self.label_44.setSizePolicy(sizePolicy)
        self.label_44.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_44.setObjectName("label_44")
        self.gridLayout_27.addWidget(self.label_44, 0, 0, 1, 1)
        self.ROI_ID_spin = QtWidgets.QSpinBox(self.tab_2)
        self.ROI_ID_spin.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ROI_ID_spin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ROI_ID_spin.setMinimum(0)
        self.ROI_ID_spin.setMaximum(9999)
        self.ROI_ID_spin.setProperty("value", 1)
        self.ROI_ID_spin.setObjectName("ROI_ID_spin")
        self.gridLayout_27.addWidget(self.ROI_ID_spin, 1, 1, 1, 2)
        self.ROI_Class_line = QtWidgets.QLineEdit(self.tab_2)
        self.ROI_Class_line.setMaxLength(80)
        self.ROI_Class_line.setObjectName("ROI_Class_line")
        self.gridLayout_27.addWidget(self.ROI_Class_line, 1, 4, 1, 1)
        self.ROI_Macroclass_line = QtWidgets.QLineEdit(self.tab_2)
        self.ROI_Macroclass_line.setMaxLength(80)
        self.ROI_Macroclass_line.setObjectName("ROI_Macroclass_line")
        self.gridLayout_27.addWidget(self.ROI_Macroclass_line, 0, 4, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_27)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.undo_save_Button = QtWidgets.QToolButton(self.tab_2)
        self.undo_save_Button.setStyleSheet("margin: 0px;padding: 0px;")
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_undo_save_roi.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.undo_save_Button.setIcon(icon20)
        self.undo_save_Button.setIconSize(QtCore.QSize(22, 22))
        self.undo_save_Button.setObjectName("undo_save_Button")
        self.horizontalLayout.addWidget(self.undo_save_Button)
        spacerItem3 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.save_input_checkBox = QtWidgets.QCheckBox(self.tab_2)
        self.save_input_checkBox.setChecked(True)
        self.save_input_checkBox.setObjectName("save_input_checkBox")
        self.horizontalLayout.addWidget(self.save_input_checkBox)
        self.signature_checkBox = QtWidgets.QCheckBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signature_checkBox.sizePolicy().hasHeightForWidth())
        self.signature_checkBox.setSizePolicy(sizePolicy)
        self.signature_checkBox.setChecked(True)
        self.signature_checkBox.setObjectName("signature_checkBox")
        self.horizontalLayout.addWidget(self.signature_checkBox)
        self.button_Save_ROI = QtWidgets.QToolButton(self.tab_2)
        self.button_Save_ROI.setStyleSheet("margin: 0px;padding: 0px;")
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_save_roi.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_Save_ROI.setIcon(icon21)
        self.button_Save_ROI.setIconSize(QtCore.QSize(22, 22))
        self.button_Save_ROI.setObjectName("button_Save_ROI")
        self.horizontalLayout.addWidget(self.button_Save_ROI)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout_7.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_training_input.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_dock.addTab(self.tab_2, icon22, "")
        self.tab_12 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_12.sizePolicy().hasHeightForWidth())
        self.tab_12.setSizePolicy(sizePolicy)
        self.tab_12.setObjectName("tab_12")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_12)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.display_cursor_checkBox = QtWidgets.QCheckBox(self.tab_12)
        self.display_cursor_checkBox.setChecked(True)
        self.display_cursor_checkBox.setObjectName("display_cursor_checkBox")
        self.horizontalLayout_8.addWidget(self.display_cursor_checkBox)
        self.vegetation_index_comboBox = QtWidgets.QComboBox(self.tab_12)
        self.vegetation_index_comboBox.setObjectName("vegetation_index_comboBox")
        self.vegetation_index_comboBox.addItem("")
        self.vegetation_index_comboBox.addItem("")
        self.vegetation_index_comboBox.addItem("")
        self.horizontalLayout_8.addWidget(self.vegetation_index_comboBox)
        self.custom_index_lineEdit = QtWidgets.QLineEdit(self.tab_12)
        self.custom_index_lineEdit.setObjectName("custom_index_lineEdit")
        self.horizontalLayout_8.addWidget(self.custom_index_lineEdit)
        self.gridLayout_4.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.rapid_ROI_checkBox = QtWidgets.QCheckBox(self.tab_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rapid_ROI_checkBox.sizePolicy().hasHeightForWidth())
        self.rapid_ROI_checkBox.setSizePolicy(sizePolicy)
        self.rapid_ROI_checkBox.setChecked(True)
        self.rapid_ROI_checkBox.setObjectName("rapid_ROI_checkBox")
        self.gridLayout_5.addWidget(self.rapid_ROI_checkBox, 0, 0, 1, 1)
        self.rapidROI_band_spinBox = QtWidgets.QSpinBox(self.tab_12)
        self.rapidROI_band_spinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rapidROI_band_spinBox.setMinimum(1)
        self.rapidROI_band_spinBox.setMaximum(10000)
        self.rapidROI_band_spinBox.setProperty("value", 1)
        self.rapidROI_band_spinBox.setObjectName("rapidROI_band_spinBox")
        self.gridLayout_5.addWidget(self.rapidROI_band_spinBox, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_5, 1, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.auto_refresh_ROI_radioButton = QtWidgets.QRadioButton(self.tab_12)
        self.auto_refresh_ROI_radioButton.setAutoExclusive(False)
        self.auto_refresh_ROI_radioButton.setObjectName("auto_refresh_ROI_radioButton")
        self.gridLayout_3.addWidget(self.auto_refresh_ROI_radioButton, 0, 1, 1, 1)
        self.auto_calculate_ROI_signature_radioButton = QtWidgets.QRadioButton(self.tab_12)
        self.auto_calculate_ROI_signature_radioButton.setAutoExclusive(False)
        self.auto_calculate_ROI_signature_radioButton.setObjectName("auto_calculate_ROI_signature_radioButton")
        self.gridLayout_3.addWidget(self.auto_calculate_ROI_signature_radioButton, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 360, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 1, 0, 1, 1)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_roi_options.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_dock.addTab(self.tab_12, icon23, "")
        self.tab_4 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_4.sizePolicy().hasHeightForWidth())
        self.tab_4.setSizePolicy(sizePolicy)
        self.tab_4.setObjectName("tab_4")
        self.tabWidget_dock.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_5.sizePolicy().hasHeightForWidth())
        self.tab_5.setSizePolicy(sizePolicy)
        self.tab_5.setObjectName("tab_5")
        self.tabWidget_dock.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_6.sizePolicy().hasHeightForWidth())
        self.tab_6.setSizePolicy(sizePolicy)
        self.tab_6.setObjectName("tab_6")
        self.tabWidget_dock.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_7.sizePolicy().hasHeightForWidth())
        self.tab_7.setSizePolicy(sizePolicy)
        self.tab_7.setObjectName("tab_7")
        self.tabWidget_dock.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_8.sizePolicy().hasHeightForWidth())
        self.tab_8.setSizePolicy(sizePolicy)
        self.tab_8.setObjectName("tab_8")
        self.tabWidget_dock.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_9.sizePolicy().hasHeightForWidth())
        self.tab_9.setSizePolicy(sizePolicy)
        self.tab_9.setObjectName("tab_9")
        self.tabWidget_dock.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_10.sizePolicy().hasHeightForWidth())
        self.tab_10.setSizePolicy(sizePolicy)
        self.tab_10.setObjectName("tab_10")
        self.tabWidget_dock.addTab(self.tab_10, "")
        self.gridLayout_6.addWidget(self.tabWidget_dock, 0, 0, 1, 1)
        DockClass.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockClass)
        self.tabWidget_dock.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DockClass)

    def retranslateUi(self, DockClass):
        _translate = QtCore.QCoreApplication.translate
        DockClass.setWindowTitle(_translate("DockClass", "SCP &Dock"))
        self.batch_toolButton.setToolTip(_translate("DockClass", "<html><head/><body><p>Batch</p></body></html>"))
        self.postprocessing_toolButton_2.setToolTip(_translate("DockClass", "<html><head/><body><p>Postprocessing</p></body></html>"))
        self.preprocessing_toolButton_2.setToolTip(_translate("DockClass", "<html><head/><body><p>Preprocessing</p></body></html>"))
        self.bandset_toolButton.setToolTip(_translate("DockClass", "<html><head/><body><p><span >Band set</span></p></body></html>"))
        self.bandcalc_toolButton_2.setToolTip(_translate("DockClass", "<html><head/><body><p><span >Band calc</span></p></body></html>"))
        self.download_images_toolButton_2.setToolTip(_translate("DockClass", "<html><head/><body><p>Download products</p></body></html>"))
        self.band_processing_toolButton.setToolTip(_translate("DockClass", "<html><head/><body><p>Band processing</p></body></html>"))
        self.basic_tools_toolButton.setToolTip(_translate("DockClass", "<html><head/><body><p>Basic tools</p></body></html>"))
        self.label_35.setText(_translate("DockClass", " News"))
        self.userguide_toolButton_2.setToolTip(_translate("DockClass", "<html><head/><body><p>User manual</p></body></html>"))
        self.userguide_toolButton_2.setText(_translate("DockClass", "User manual"))
        self.help_toolButton_2.setToolTip(_translate("DockClass", "<html><head/><body><p>Ask a question</p></body></html>"))
        self.help_toolButton_2.setText(_translate("DockClass", "Ask a question"))
        self.support_toolButton.setToolTip(_translate("DockClass", "<html><head/><body><p><span style=\" color:#ffffff;\">Support the SCP</span></p></body></html>"))
        self.support_toolButton.setText(_translate("DockClass", "Support the SCP"))
        self.tabWidget_dock.setTabText(self.tabWidget_dock.indexOf(self.tab), _translate("DockClass", "Home"))
        self.button_new_input.setToolTip(_translate("DockClass", "<html><head/><body><p><span >Create a new training input</span></p></body></html>"))
        self.trainingFile_lineEdit.setToolTip(_translate("DockClass", "<html><head/><body><p>Input file path</p></body></html>"))
        self.trainingFile_lineEdit.setPlaceholderText(_translate("DockClass", "Training input"))
        self.trainingFile_toolButton.setToolTip(_translate("DockClass", "<html><head/><body><p><span >Open a training input</span></p></body></html>"))
        self.button_reset_input.setToolTip(_translate("DockClass", "<html><head/><body><p>Remove training input</p></body></html>"))
        self.label_48.setText(_translate("DockClass", " ROI & Signature list"))
        self.merge_signature_toolButton.setToolTip(_translate("DockClass", "<html><head/><body><p >Merge highlighted spectral signatures obtaining the average signature</p></body></html>"))
        self.calculate_signature_toolButton.setToolTip(_translate("DockClass", "<html><head/><body><p>Calculate signatures for highlighted items</p></body></html>"))
        self.delete_Signature_Button.setToolTip(_translate("DockClass", "<html><head/><body><p>Delete highlighted items</p></body></html>"))
        self.delete_Signature_Button.setText(_translate("DockClass", "..."))
        self.signature_spectral_plot_toolButton.setToolTip(_translate("DockClass", "<html><head/><body><p >Add highlighted signatures to spectral signature plot</p></body></html>"))
        self.signature_spectral_plot_toolButton.setText(_translate("DockClass", "Plot"))
        self.scatterPlot_toolButton.setToolTip(_translate("DockClass", "<html><head/><body><p>Add highlighted items to scatter plot</p></body></html>"))
        self.scatterPlot_toolButton.setText(_translate("DockClass", "..."))
        self.import_library_toolButton.setToolTip(_translate("DockClass", "<html><head/><body><p>Import spectral signatures </p></body></html>"))
        self.import_library_toolButton.setText(_translate("DockClass", "Import library"))
        self.export_signature_list_toolButton.setToolTip(_translate("DockClass", "<html><head/><body><p >Export highlighted spectral signatures</p></body></html>\n"
""))
        self.export_signature_list_toolButton.setText(_translate("DockClass", "Import library"))
        self.ROI_filter_lineEdit.setToolTip(_translate("DockClass", "<html><head/><body><p>Filter</p></body></html>"))
        self.ROI_filter_lineEdit.setPlaceholderText(_translate("DockClass", "Filter"))
        self.label_41.setText(_translate("DockClass", "C Name"))
        self.ROI_Macroclass_ID_spin.setToolTip(_translate("DockClass", "<html><head/><body><p>The macroclass ID of the ROI signature</p></body></html>"))
        self.label_42.setText(_translate("DockClass", "C ID"))
        self.label_45.setText(_translate("DockClass", "MC Name"))
        self.label_44.setText(_translate("DockClass", "MC ID"))
        self.ROI_ID_spin.setToolTip(_translate("DockClass", "<html><head/><body><p>The class ID of the ROI signature</p></body></html>"))
        self.ROI_Class_line.setToolTip(_translate("DockClass", "<html><head/><body><p>The class name of the ROI signature</p></body></html>"))
        self.ROI_Class_line.setText(_translate("DockClass", "C 1"))
        self.ROI_Macroclass_line.setToolTip(_translate("DockClass", "<html><head/><body><p>The macroclass name of the ROI signature</p></body></html>"))
        self.ROI_Macroclass_line.setText(_translate("DockClass", "MC 1"))
        self.undo_save_Button.setToolTip(_translate("DockClass", "<html><head/><body><p >Undo ROI save</p></body></html>"))
        self.undo_save_Button.setText(_translate("DockClass", "Import library"))
        self.save_input_checkBox.setToolTip(_translate("DockClass", "<html><head/><body><p>Automatically save training input when a ROI is saved in it</p></body></html>"))
        self.save_input_checkBox.setText(_translate("DockClass", "Autosave"))
        self.signature_checkBox.setToolTip(_translate("DockClass", "<html><head/><body><p>Add ROI spectral signature to signature list</p></body></html>"))
        self.signature_checkBox.setText(_translate("DockClass", "Signature"))
        self.button_Save_ROI.setToolTip(_translate("DockClass", "<html><head/><body><p >Save temporary ROI to training input</p></body></html>"))
        self.button_Save_ROI.setText(_translate("DockClass", "Import library"))
        self.tabWidget_dock.setTabText(self.tabWidget_dock.indexOf(self.tab_2), _translate("DockClass", "Training input"))
        self.display_cursor_checkBox.setToolTip(_translate("DockClass", "<html><head/><body><p>Display a vegetation index value with the cursor</p></body></html>"))
        self.display_cursor_checkBox.setText(_translate("DockClass", "Display"))
        self.vegetation_index_comboBox.setToolTip(_translate("DockClass", "<html><head/><body><p>Select a vegetation index</p></body></html>"))
        self.vegetation_index_comboBox.setItemText(0, _translate("DockClass", "NDVI"))
        self.vegetation_index_comboBox.setItemText(1, _translate("DockClass", "EVI"))
        self.vegetation_index_comboBox.setItemText(2, _translate("DockClass", "Custom"))
        self.custom_index_lineEdit.setToolTip(_translate("DockClass", "<html><head/><body><p>Custom expression (e.g. bandset#b4 / bandset#b3 )</p></body></html>"))
        self.rapid_ROI_checkBox.setToolTip(_translate("DockClass", "<html><head/><body><p>Calculate temporary ROI only on one band</p></body></html>"))
        self.rapid_ROI_checkBox.setText(_translate("DockClass", "Rapid ROI b."))
        self.rapidROI_band_spinBox.setToolTip(_translate("DockClass", "<html><head/><body><p>Band number</p></body></html>"))
        self.auto_refresh_ROI_radioButton.setToolTip(_translate("DockClass", "<html><head/><body><p>Automatically refresh the temporary ROI, as the parameters change</p></body></html>"))
        self.auto_refresh_ROI_radioButton.setText(_translate("DockClass", "A&uto-refresh ROI"))
        self.auto_calculate_ROI_signature_radioButton.setToolTip(_translate("DockClass", "<html><head/><body><p>Automatically calculate signature plot of temporary ROI</p></body></html>"))
        self.auto_calculate_ROI_signature_radioButton.setText(_translate("DockClass", "Auto-plot"))
        self.tabWidget_dock.setTabText(self.tabWidget_dock.indexOf(self.tab_12), _translate("DockClass", " ROI options"))

from . import resources_rc
