# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_semiautomaticclassificationplugin_dock_class.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DockClass(object):
    def setupUi(self, DockClass):
        DockClass.setObjectName("DockClass")
        DockClass.resize(363, 536)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DockClass.sizePolicy().hasHeightForWidth())
        DockClass.setSizePolicy(sizePolicy)
        DockClass.setMinimumSize(QtCore.QSize(363, 459))
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget_dock = QtWidgets.QTabWidget(self.dockWidgetContents)
        self.tabWidget_dock.setStyleSheet("QTabBar::tab {padding-bottom: 2px; padding-top: 2px;margin-bottom: 0px; margin-top: 0px; padding-left: 1ex;padding-right: 0.8ex;}")
        self.tabWidget_dock.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget_dock.setIconSize(QtCore.QSize(15, 15))
        self.tabWidget_dock.setDocumentMode(True)
        self.tabWidget_dock.setObjectName("tabWidget_dock")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.main_textBrowser = QtWidgets.QTextBrowser(self.tab)
        self.main_textBrowser.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'DejaVu Sans\';\"><br /></span></p></body></html>")
        self.main_textBrowser.setOpenExternalLinks(True)
        self.main_textBrowser.setObjectName("main_textBrowser")
        self.gridLayout_12.addWidget(self.main_textBrowser, 1, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("background-color : qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #535353, stop:1 #a6a6a6); color : white; font: bold;")
        self.label_35.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_35.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_35.setObjectName("label_35")
        self.gridLayout_12.addWidget(self.label_35, 0, 0, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_12, 1, 1, 1, 1)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_40 = QtWidgets.QGridLayout()
        self.gridLayout_40.setHorizontalSpacing(8)
        self.gridLayout_40.setObjectName("gridLayout_40")
        self.batch_toolButton = QtWidgets.QToolButton(self.tab)
        self.batch_toolButton.setStyleSheet("margin: 0px;padding: 0px;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_batch.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.batch_toolButton.setIcon(icon)
        self.batch_toolButton.setIconSize(QtCore.QSize(22, 22))
        self.batch_toolButton.setObjectName("batch_toolButton")
        self.gridLayout_40.addWidget(self.batch_toolButton, 0, 9, 1, 1)
        self.postprocessing_toolButton_2 = QtWidgets.QToolButton(self.tab)
        self.postprocessing_toolButton_2.setStyleSheet("margin: 0px;padding: 0px;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_post_process.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.postprocessing_toolButton_2.setIcon(icon1)
        self.postprocessing_toolButton_2.setIconSize(QtCore.QSize(22, 22))
        self.postprocessing_toolButton_2.setObjectName("postprocessing_toolButton_2")
        self.gridLayout_40.addWidget(self.postprocessing_toolButton_2, 0, 7, 1, 1)
        self.preprocessing_toolButton_2 = QtWidgets.QToolButton(self.tab)
        self.preprocessing_toolButton_2.setStyleSheet("margin: 0px;padding: 0px;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_class_tool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.preprocessing_toolButton_2.setIcon(icon2)
        self.preprocessing_toolButton_2.setIconSize(QtCore.QSize(22, 22))
        self.preprocessing_toolButton_2.setObjectName("preprocessing_toolButton_2")
        self.gridLayout_40.addWidget(self.preprocessing_toolButton_2, 0, 5, 1, 1)
        self.bandset_toolButton = QtWidgets.QToolButton(self.tab)
        self.bandset_toolButton.setStyleSheet("margin: 0px;padding: 0px;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_bandset_tool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bandset_toolButton.setIcon(icon3)
        self.bandset_toolButton.setIconSize(QtCore.QSize(22, 22))
        self.bandset_toolButton.setObjectName("bandset_toolButton")
        self.gridLayout_40.addWidget(self.bandset_toolButton, 0, 0, 1, 1)
        self.bandcalc_toolButton_2 = QtWidgets.QToolButton(self.tab)
        self.bandcalc_toolButton_2.setStyleSheet("margin: 0px;padding: 0px;")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_bandcalc_tool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bandcalc_toolButton_2.setIcon(icon4)
        self.bandcalc_toolButton_2.setIconSize(QtCore.QSize(22, 22))
        self.bandcalc_toolButton_2.setObjectName("bandcalc_toolButton_2")
        self.gridLayout_40.addWidget(self.bandcalc_toolButton_2, 0, 8, 1, 1)
        self.download_images_toolButton_2 = QtWidgets.QToolButton(self.tab)
        self.download_images_toolButton_2.setStyleSheet("margin: 0px;padding: 0px;")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_download_arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.download_images_toolButton_2.setIcon(icon5)
        self.download_images_toolButton_2.setIconSize(QtCore.QSize(22, 22))
        self.download_images_toolButton_2.setObjectName("download_images_toolButton_2")
        self.gridLayout_40.addWidget(self.download_images_toolButton_2, 0, 2, 1, 1)
        self.band_processing_toolButton = QtWidgets.QToolButton(self.tab)
        self.band_processing_toolButton.setStyleSheet("margin: 0px;padding: 0px;")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_band_processing.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.band_processing_toolButton.setIcon(icon6)
        self.band_processing_toolButton.setIconSize(QtCore.QSize(22, 22))
        self.band_processing_toolButton.setObjectName("band_processing_toolButton")
        self.gridLayout_40.addWidget(self.band_processing_toolButton, 0, 6, 1, 1)
        self.basic_tools_toolButton = QtWidgets.QToolButton(self.tab)
        self.basic_tools_toolButton.setStyleSheet("margin: 0px;padding: 0px;")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_roi_tool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.basic_tools_toolButton.setIcon(icon7)
        self.basic_tools_toolButton.setIconSize(QtCore.QSize(22, 22))
        self.basic_tools_toolButton.setObjectName("basic_tools_toolButton")
        self.gridLayout_40.addWidget(self.basic_tools_toolButton, 0, 1, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_40, 1, 0, 1, 1)
        self.plugin_version_label2 = QtWidgets.QLabel(self.tab)
        self.plugin_version_label2.setText("")
        self.plugin_version_label2.setAlignment(QtCore.Qt.AlignCenter)
        self.plugin_version_label2.setObjectName("plugin_version_label2")
        self.gridLayout_11.addWidget(self.plugin_version_label2, 0, 0, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_11, 0, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.userguide_toolButton_2 = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.userguide_toolButton_2.setFont(font)
        self.userguide_toolButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.userguide_toolButton_2.setStyleSheet("color: white;\n"
"background-color: rgb(51, 122, 183);\n"
"selection-color: yellow;\n"
"selection-background-color: blue;\n"
"font: bold 14px;\n"
"border-style: inset;\n"
"border-width: 2px;\n"
"border-radius: 6px;\n"
"border-color: white;\n"
"padding: 2px;")
        self.userguide_toolButton_2.setObjectName("userguide_toolButton_2")
        self.verticalLayout.addWidget(self.userguide_toolButton_2)
        self.help_toolButton_2 = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.help_toolButton_2.setFont(font)
        self.help_toolButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.help_toolButton_2.setStyleSheet("color: white;\n"
"background-color: rgb(51, 122, 183);\n"
"selection-color: yellow;\n"
"selection-background-color: blue;\n"
"font: bold 14px;\n"
"border-style: inset;\n"
"border-width: 2px;\n"
"border-radius: 6px;\n"
"border-color: white;\n"
"padding: 2px;")
        self.help_toolButton_2.setObjectName("help_toolButton_2")
        self.verticalLayout.addWidget(self.help_toolButton_2)
        self.support_toolButton = QtWidgets.QPushButton(self.tab)
        self.support_toolButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.support_toolButton.setStyleSheet("color: white;\n"
"background-color: rgb(92, 184, 92);\n"
"selection-color: yellow;\n"
"selection-background-color: blue;\n"
"font: bold 14px;\n"
"border-style: inset;\n"
"border-width: 2px;\n"
"border-radius: 6px;\n"
"border-color: white;\n"
"padding: 2px;")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/semiautomaticclassificationplugin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.support_toolButton.setIcon(icon8)
        self.support_toolButton.setFlat(False)
        self.support_toolButton.setObjectName("support_toolButton")
        self.verticalLayout.addWidget(self.support_toolButton)
        self.gridLayout_14.addLayout(self.verticalLayout, 2, 1, 1, 1)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_dock.addTab(self.tab, icon9, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_19 = QtWidgets.QGridLayout()
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.trainingFile_toolButton = QtWidgets.QToolButton(self.tab_2)
        self.trainingFile_toolButton.setStyleSheet("margin: 0px;padding: 0px;")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_open_file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.trainingFile_toolButton.setIcon(icon10)
        self.trainingFile_toolButton.setIconSize(QtCore.QSize(22, 22))
        self.trainingFile_toolButton.setObjectName("trainingFile_toolButton")
        self.gridLayout_19.addWidget(self.trainingFile_toolButton, 0, 0, 1, 1)
        self.button_new_input = QtWidgets.QToolButton(self.tab_2)
        self.button_new_input.setStyleSheet("margin: 0px;padding: 0px;")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_new_file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_new_input.setIcon(icon11)
        self.button_new_input.setIconSize(QtCore.QSize(22, 22))
        self.button_new_input.setObjectName("button_new_input")
        self.gridLayout_19.addWidget(self.button_new_input, 0, 1, 1, 1)
        self.trainingFile_lineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.trainingFile_lineEdit.setEnabled(False)
        self.trainingFile_lineEdit.setObjectName("trainingFile_lineEdit")
        self.gridLayout_19.addWidget(self.trainingFile_lineEdit, 0, 2, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_19, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setIconSize(QtCore.QSize(15, 15))
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_ROI = QtWidgets.QWidget()
        self.tab_ROI.setObjectName("tab_ROI")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_ROI)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.undo_save_Button = QtWidgets.QToolButton(self.tab_ROI)
        self.undo_save_Button.setStyleSheet("margin: 0px;padding: 0px;")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_undo_save_roi.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.undo_save_Button.setIcon(icon12)
        self.undo_save_Button.setIconSize(QtCore.QSize(22, 22))
        self.undo_save_Button.setObjectName("undo_save_Button")
        self.horizontalLayout.addWidget(self.undo_save_Button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.save_input_checkBox = QtWidgets.QCheckBox(self.tab_ROI)
        self.save_input_checkBox.setChecked(True)
        self.save_input_checkBox.setObjectName("save_input_checkBox")
        self.horizontalLayout.addWidget(self.save_input_checkBox)
        self.signature_checkBox = QtWidgets.QCheckBox(self.tab_ROI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signature_checkBox.sizePolicy().hasHeightForWidth())
        self.signature_checkBox.setSizePolicy(sizePolicy)
        self.signature_checkBox.setChecked(True)
        self.signature_checkBox.setObjectName("signature_checkBox")
        self.horizontalLayout.addWidget(self.signature_checkBox)
        self.button_Save_ROI = QtWidgets.QToolButton(self.tab_ROI)
        self.button_Save_ROI.setStyleSheet("margin: 0px;padding: 0px;")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_save_roi.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_Save_ROI.setIcon(icon13)
        self.button_Save_ROI.setIconSize(QtCore.QSize(22, 22))
        self.button_Save_ROI.setObjectName("button_Save_ROI")
        self.horizontalLayout.addWidget(self.button_Save_ROI)
        self.gridLayout_8.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.merge_signature_toolButton = QtWidgets.QToolButton(self.tab_ROI)
        self.merge_signature_toolButton.setStyleSheet("margin: 0px;padding: 0px;")
        self.merge_signature_toolButton.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_merge_sign_tool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.merge_signature_toolButton.setIcon(icon14)
        self.merge_signature_toolButton.setIconSize(QtCore.QSize(22, 22))
        self.merge_signature_toolButton.setObjectName("merge_signature_toolButton")
        self.verticalLayout_4.addWidget(self.merge_signature_toolButton)
        self.calculate_signature_toolButton = QtWidgets.QToolButton(self.tab_ROI)
        self.calculate_signature_toolButton.setStyleSheet("margin: 0px;padding: 0px;")
        self.calculate_signature_toolButton.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_calculate_signature.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.calculate_signature_toolButton.setIcon(icon15)
        self.calculate_signature_toolButton.setIconSize(QtCore.QSize(22, 22))
        self.calculate_signature_toolButton.setObjectName("calculate_signature_toolButton")
        self.verticalLayout_4.addWidget(self.calculate_signature_toolButton)
        self.delete_Signature_Button = QtWidgets.QToolButton(self.tab_ROI)
        self.delete_Signature_Button.setStyleSheet("margin: 0px;padding: 0px;")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_delete_signature.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_Signature_Button.setIcon(icon16)
        self.delete_Signature_Button.setIconSize(QtCore.QSize(22, 22))
        self.delete_Signature_Button.setObjectName("delete_Signature_Button")
        self.verticalLayout_4.addWidget(self.delete_Signature_Button)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.signature_spectral_plot_toolButton = QtWidgets.QToolButton(self.tab_ROI)
        self.signature_spectral_plot_toolButton.setStyleSheet("margin: 0px;padding: 0px;")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_sign_tool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.signature_spectral_plot_toolButton.setIcon(icon17)
        self.signature_spectral_plot_toolButton.setIconSize(QtCore.QSize(22, 22))
        self.signature_spectral_plot_toolButton.setObjectName("signature_spectral_plot_toolButton")
        self.verticalLayout_4.addWidget(self.signature_spectral_plot_toolButton)
        self.scatterPlot_toolButton = QtWidgets.QToolButton(self.tab_ROI)
        self.scatterPlot_toolButton.setStyleSheet("margin: 0px;padding: 0px;")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_scatter_tool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.scatterPlot_toolButton.setIcon(icon18)
        self.scatterPlot_toolButton.setIconSize(QtCore.QSize(22, 22))
        self.scatterPlot_toolButton.setObjectName("scatterPlot_toolButton")
        self.verticalLayout_4.addWidget(self.scatterPlot_toolButton)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.import_library_toolButton = QtWidgets.QToolButton(self.tab_ROI)
        self.import_library_toolButton.setStyleSheet("margin: 0px;padding: 0px;")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_import_spectral_library.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.import_library_toolButton.setIcon(icon19)
        self.import_library_toolButton.setIconSize(QtCore.QSize(22, 22))
        self.import_library_toolButton.setObjectName("import_library_toolButton")
        self.verticalLayout_4.addWidget(self.import_library_toolButton)
        self.export_signature_list_toolButton = QtWidgets.QToolButton(self.tab_ROI)
        self.export_signature_list_toolButton.setStyleSheet("margin: 0px;padding: 0px;")
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_export_spectral_library.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.export_signature_list_toolButton.setIcon(icon20)
        self.export_signature_list_toolButton.setIconSize(QtCore.QSize(22, 22))
        self.export_signature_list_toolButton.setObjectName("export_signature_list_toolButton")
        self.verticalLayout_4.addWidget(self.export_signature_list_toolButton)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.signature_list_tableWidget = QtWidgets.QTableWidget(self.tab_ROI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signature_list_tableWidget.sizePolicy().hasHeightForWidth())
        self.signature_list_tableWidget.setSizePolicy(sizePolicy)
        self.signature_list_tableWidget.setMinimumSize(QtCore.QSize(0, 150))
        self.signature_list_tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.SelectedClicked)
        self.signature_list_tableWidget.setObjectName("signature_list_tableWidget")
        self.signature_list_tableWidget.setColumnCount(6)
        self.signature_list_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.signature_list_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.signature_list_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.signature_list_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.signature_list_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.signature_list_tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.signature_list_tableWidget.setHorizontalHeaderItem(5, item)
        self.signature_list_tableWidget.horizontalHeader().setDefaultSectionSize(50)
        self.signature_list_tableWidget.verticalHeader().setDefaultSectionSize(20)
        self.gridLayout.addWidget(self.signature_list_tableWidget, 0, 1, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_27 = QtWidgets.QGridLayout()
        self.gridLayout_27.setVerticalSpacing(4)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.label_41 = QtWidgets.QLabel(self.tab_ROI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_41.sizePolicy().hasHeightForWidth())
        self.label_41.setSizePolicy(sizePolicy)
        self.label_41.setObjectName("label_41")
        self.gridLayout_27.addWidget(self.label_41, 1, 3, 1, 1)
        self.ROI_Macroclass_ID_spin = QtWidgets.QSpinBox(self.tab_ROI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ROI_Macroclass_ID_spin.sizePolicy().hasHeightForWidth())
        self.ROI_Macroclass_ID_spin.setSizePolicy(sizePolicy)
        self.ROI_Macroclass_ID_spin.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ROI_Macroclass_ID_spin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ROI_Macroclass_ID_spin.setMinimum(0)
        self.ROI_Macroclass_ID_spin.setMaximum(9999)
        self.ROI_Macroclass_ID_spin.setProperty("value", 1)
        self.ROI_Macroclass_ID_spin.setObjectName("ROI_Macroclass_ID_spin")
        self.gridLayout_27.addWidget(self.ROI_Macroclass_ID_spin, 0, 1, 1, 2)
        self.label_42 = QtWidgets.QLabel(self.tab_ROI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_42.sizePolicy().hasHeightForWidth())
        self.label_42.setSizePolicy(sizePolicy)
        self.label_42.setMaximumSize(QtCore.QSize(89, 16777215))
        self.label_42.setObjectName("label_42")
        self.gridLayout_27.addWidget(self.label_42, 1, 0, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.tab_ROI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_45.sizePolicy().hasHeightForWidth())
        self.label_45.setSizePolicy(sizePolicy)
        self.label_45.setObjectName("label_45")
        self.gridLayout_27.addWidget(self.label_45, 0, 3, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.tab_ROI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_44.sizePolicy().hasHeightForWidth())
        self.label_44.setSizePolicy(sizePolicy)
        self.label_44.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_44.setObjectName("label_44")
        self.gridLayout_27.addWidget(self.label_44, 0, 0, 1, 1)
        self.ROI_ID_spin = QtWidgets.QSpinBox(self.tab_ROI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ROI_ID_spin.sizePolicy().hasHeightForWidth())
        self.ROI_ID_spin.setSizePolicy(sizePolicy)
        self.ROI_ID_spin.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ROI_ID_spin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ROI_ID_spin.setMinimum(0)
        self.ROI_ID_spin.setMaximum(9999)
        self.ROI_ID_spin.setProperty("value", 1)
        self.ROI_ID_spin.setObjectName("ROI_ID_spin")
        self.gridLayout_27.addWidget(self.ROI_ID_spin, 1, 1, 1, 2)
        self.ROI_Class_line = QtWidgets.QLineEdit(self.tab_ROI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ROI_Class_line.sizePolicy().hasHeightForWidth())
        self.ROI_Class_line.setSizePolicy(sizePolicy)
        self.ROI_Class_line.setMaxLength(80)
        self.ROI_Class_line.setObjectName("ROI_Class_line")
        self.gridLayout_27.addWidget(self.ROI_Class_line, 1, 4, 1, 1)
        self.ROI_Macroclass_line = QtWidgets.QLineEdit(self.tab_ROI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ROI_Macroclass_line.sizePolicy().hasHeightForWidth())
        self.ROI_Macroclass_line.setSizePolicy(sizePolicy)
        self.ROI_Macroclass_line.setMaxLength(80)
        self.ROI_Macroclass_line.setObjectName("ROI_Macroclass_line")
        self.gridLayout_27.addWidget(self.ROI_Macroclass_line, 0, 4, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_27, 1, 0, 1, 1)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_roi_list.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_ROI, icon21, "")
        self.tab_MC = QtWidgets.QWidget()
        self.tab_MC.setObjectName("tab_MC")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.tab_MC)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.gridLayout_23 = QtWidgets.QGridLayout()
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.macroclass_color_tableWidget = QtWidgets.QTableWidget(self.tab_MC)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.macroclass_color_tableWidget.sizePolicy().hasHeightForWidth())
        self.macroclass_color_tableWidget.setSizePolicy(sizePolicy)
        self.macroclass_color_tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.SelectedClicked)
        self.macroclass_color_tableWidget.setObjectName("macroclass_color_tableWidget")
        self.macroclass_color_tableWidget.setColumnCount(3)
        self.macroclass_color_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.macroclass_color_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.macroclass_color_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.macroclass_color_tableWidget.setHorizontalHeaderItem(2, item)
        self.macroclass_color_tableWidget.horizontalHeader().setDefaultSectionSize(50)
        self.macroclass_color_tableWidget.verticalHeader().setDefaultSectionSize(20)
        self.gridLayout_23.addWidget(self.macroclass_color_tableWidget, 0, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.add_MC_row_Button = QtWidgets.QToolButton(self.tab_MC)
        self.add_MC_row_Button.setStyleSheet("margin: 0px;padding: 0px;")
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_MC_row_Button.setIcon(icon22)
        self.add_MC_row_Button.setIconSize(QtCore.QSize(22, 22))
        self.add_MC_row_Button.setObjectName("add_MC_row_Button")
        self.verticalLayout_2.addWidget(self.add_MC_row_Button)
        self.delete_MC_row_Button = QtWidgets.QToolButton(self.tab_MC)
        self.delete_MC_row_Button.setStyleSheet("margin: 0px;padding: 0px;")
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_MC_row_Button.setIcon(icon23)
        self.delete_MC_row_Button.setIconSize(QtCore.QSize(22, 22))
        self.delete_MC_row_Button.setObjectName("delete_MC_row_Button")
        self.verticalLayout_2.addWidget(self.delete_MC_row_Button)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.gridLayout_23.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_23, 0, 0, 1, 1)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_macroclass_list.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_MC, icon24, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_11)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.rapid_ROI_checkBox = QtWidgets.QCheckBox(self.tab_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rapid_ROI_checkBox.sizePolicy().hasHeightForWidth())
        self.rapid_ROI_checkBox.setSizePolicy(sizePolicy)
        self.rapid_ROI_checkBox.setObjectName("rapid_ROI_checkBox")
        self.gridLayout_5.addWidget(self.rapid_ROI_checkBox, 0, 0, 1, 1)
        self.rapidROI_band_spinBox = QtWidgets.QSpinBox(self.tab_11)
        self.rapidROI_band_spinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rapidROI_band_spinBox.setMinimum(1)
        self.rapidROI_band_spinBox.setMaximum(10000)
        self.rapidROI_band_spinBox.setProperty("value", 1)
        self.rapidROI_band_spinBox.setObjectName("rapidROI_band_spinBox")
        self.gridLayout_5.addWidget(self.rapidROI_band_spinBox, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_5, 1, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.display_cursor_checkBox = QtWidgets.QCheckBox(self.tab_11)
        self.display_cursor_checkBox.setChecked(True)
        self.display_cursor_checkBox.setObjectName("display_cursor_checkBox")
        self.horizontalLayout_8.addWidget(self.display_cursor_checkBox)
        self.vegetation_index_comboBox = QtWidgets.QComboBox(self.tab_11)
        self.vegetation_index_comboBox.setObjectName("vegetation_index_comboBox")
        self.vegetation_index_comboBox.addItem("")
        self.vegetation_index_comboBox.addItem("")
        self.vegetation_index_comboBox.addItem("")
        self.horizontalLayout_8.addWidget(self.vegetation_index_comboBox)
        self.custom_index_lineEdit = QtWidgets.QLineEdit(self.tab_11)
        self.custom_index_lineEdit.setObjectName("custom_index_lineEdit")
        self.horizontalLayout_8.addWidget(self.custom_index_lineEdit)
        self.gridLayout_4.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.auto_refresh_ROI_radioButton = QtWidgets.QRadioButton(self.tab_11)
        self.auto_refresh_ROI_radioButton.setAutoExclusive(False)
        self.auto_refresh_ROI_radioButton.setObjectName("auto_refresh_ROI_radioButton")
        self.gridLayout_3.addWidget(self.auto_refresh_ROI_radioButton, 0, 1, 1, 1)
        self.auto_calculate_ROI_signature_radioButton = QtWidgets.QRadioButton(self.tab_11)
        self.auto_calculate_ROI_signature_radioButton.setAutoExclusive(False)
        self.auto_calculate_ROI_signature_radioButton.setObjectName("auto_calculate_ROI_signature_radioButton")
        self.gridLayout_3.addWidget(self.auto_calculate_ROI_signature_radioButton, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem6, 1, 0, 1, 1)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_roi_options.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_11, icon25, "")
        self.gridLayout_6.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.tabWidget.raise_()
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_training_input.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_dock.addTab(self.tab_2, icon26, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_33 = QtWidgets.QGridLayout()
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_20 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_3.addWidget(self.label_20)
        self.macroclass_checkBox = QtWidgets.QCheckBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.macroclass_checkBox.sizePolicy().hasHeightForWidth())
        self.macroclass_checkBox.setSizePolicy(sizePolicy)
        self.macroclass_checkBox.setObjectName("macroclass_checkBox")
        self.horizontalLayout_3.addWidget(self.macroclass_checkBox)
        self.class_checkBox = QtWidgets.QCheckBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.class_checkBox.sizePolicy().hasHeightForWidth())
        self.class_checkBox.setSizePolicy(sizePolicy)
        self.class_checkBox.setObjectName("class_checkBox")
        self.horizontalLayout_3.addWidget(self.class_checkBox)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.algorithm_weight_button = QtWidgets.QToolButton(self.tab_3)
        self.algorithm_weight_button.setStyleSheet("margin: 0px;padding: 0px;")
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_weight_tool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.algorithm_weight_button.setIcon(icon27)
        self.algorithm_weight_button.setIconSize(QtCore.QSize(22, 22))
        self.algorithm_weight_button.setObjectName("algorithm_weight_button")
        self.horizontalLayout_3.addWidget(self.algorithm_weight_button)
        self.gridLayout_33.addLayout(self.horizontalLayout_3, 0, 0, 1, 4)
        self.label_43 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setStyleSheet("background-color : qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #535353, stop:1 #a6a6a6); color : white; font: bold;")
        self.label_43.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_43.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_43.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_43.setObjectName("label_43")
        self.gridLayout_33.addWidget(self.label_43, 1, 0, 1, 4)
        self.label_16 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_16.setObjectName("label_16")
        self.gridLayout_33.addWidget(self.label_16, 3, 0, 1, 1)
        self.algorithm_combo = QtWidgets.QComboBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.algorithm_combo.sizePolicy().hasHeightForWidth())
        self.algorithm_combo.setSizePolicy(sizePolicy)
        self.algorithm_combo.setMinimumSize(QtCore.QSize(100, 0))
        self.algorithm_combo.setObjectName("algorithm_combo")
        self.algorithm_combo.addItem("")
        self.algorithm_combo.addItem("")
        self.algorithm_combo.addItem("")
        self.gridLayout_33.addWidget(self.algorithm_combo, 2, 0, 1, 4)
        self.alg_threshold_SpinBox = QtWidgets.QDoubleSpinBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alg_threshold_SpinBox.sizePolicy().hasHeightForWidth())
        self.alg_threshold_SpinBox.setSizePolicy(sizePolicy)
        self.alg_threshold_SpinBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.alg_threshold_SpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.alg_threshold_SpinBox.setDecimals(4)
        self.alg_threshold_SpinBox.setMaximum(10000.0)
        self.alg_threshold_SpinBox.setObjectName("alg_threshold_SpinBox")
        self.gridLayout_33.addWidget(self.alg_threshold_SpinBox, 3, 1, 1, 1)
        self.algorithm_threshold_button = QtWidgets.QToolButton(self.tab_3)
        self.algorithm_threshold_button.setStyleSheet("margin: 0px;padding: 0px;")
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_threshold_tool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.algorithm_threshold_button.setIcon(icon28)
        self.algorithm_threshold_button.setIconSize(QtCore.QSize(22, 22))
        self.algorithm_threshold_button.setObjectName("algorithm_threshold_button")
        self.gridLayout_33.addWidget(self.algorithm_threshold_button, 3, 3, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_33, 0, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_43 = QtWidgets.QGridLayout()
        self.gridLayout_43.setObjectName("gridLayout_43")
        self.label_21 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setObjectName("label_21")
        self.gridLayout_43.addWidget(self.label_21, 1, 0, 1, 1)
        self.LC_signature_checkBox = QtWidgets.QCheckBox(self.tab_3)
        self.LC_signature_checkBox.setObjectName("LC_signature_checkBox")
        self.gridLayout_43.addWidget(self.LC_signature_checkBox, 1, 1, 1, 1)
        self.LC_signature_button = QtWidgets.QToolButton(self.tab_3)
        self.LC_signature_button.setStyleSheet("margin: 0px;padding: 0px;")
        self.LC_signature_button.setText("")
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_LCS_threshold_tool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.LC_signature_button.setIcon(icon29)
        self.LC_signature_button.setIconSize(QtCore.QSize(22, 22))
        self.LC_signature_button.setObjectName("LC_signature_button")
        self.gridLayout_43.addWidget(self.LC_signature_button, 1, 3, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setStyleSheet("background-color : qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #535353, stop:1 #a6a6a6); color : white; font: bold;")
        self.label_46.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_46.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_46.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_46.setObjectName("label_46")
        self.gridLayout_43.addWidget(self.label_46, 0, 0, 1, 4)
        self.LCS_leave_unclassified_checkBox = QtWidgets.QCheckBox(self.tab_3)
        self.LCS_leave_unclassified_checkBox.setObjectName("LCS_leave_unclassified_checkBox")
        self.gridLayout_43.addWidget(self.LCS_leave_unclassified_checkBox, 2, 2, 1, 1)
        self.LCS_class_algorithm_checkBox = QtWidgets.QCheckBox(self.tab_3)
        self.LCS_class_algorithm_checkBox.setObjectName("LCS_class_algorithm_checkBox")
        self.gridLayout_43.addWidget(self.LCS_class_algorithm_checkBox, 2, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_43)
        self.label_47 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setStyleSheet("background-color : qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #535353, stop:1 #a6a6a6); color : white; font: bold;")
        self.label_47.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_47.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_47.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_47.setObjectName("label_47")
        self.verticalLayout_3.addWidget(self.label_47)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setSpacing(4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.resetQmlButton = QtWidgets.QToolButton(self.tab_3)
        self.resetQmlButton.setStyleSheet("margin: 0px;padding: 0px;")
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_reset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.resetQmlButton.setIcon(icon30)
        self.resetQmlButton.setIconSize(QtCore.QSize(22, 22))
        self.resetQmlButton.setObjectName("resetQmlButton")
        self.gridLayout_7.addWidget(self.resetQmlButton, 0, 3, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setObjectName("label_19")
        self.gridLayout_7.addWidget(self.label_19, 0, 0, 1, 1)
        self.qml_Button = QtWidgets.QToolButton(self.tab_3)
        self.qml_Button.setStyleSheet("margin: 0px;padding: 0px;")
        self.qml_Button.setIcon(icon10)
        self.qml_Button.setIconSize(QtCore.QSize(22, 22))
        self.qml_Button.setObjectName("qml_Button")
        self.gridLayout_7.addWidget(self.qml_Button, 0, 2, 1, 1)
        self.qml_lineEdit = QtWidgets.QLineEdit(self.tab_3)
        self.qml_lineEdit.setEnabled(False)
        self.qml_lineEdit.setObjectName("qml_lineEdit")
        self.gridLayout_7.addWidget(self.qml_lineEdit, 0, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_7)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.mask_checkBox = QtWidgets.QCheckBox(self.tab_3)
        self.mask_checkBox.setObjectName("mask_checkBox")
        self.gridLayout_13.addWidget(self.mask_checkBox, 0, 0, 1, 1)
        self.resetMaskButton = QtWidgets.QToolButton(self.tab_3)
        self.resetMaskButton.setStyleSheet("margin: 0px;padding: 0px;")
        self.resetMaskButton.setIcon(icon30)
        self.resetMaskButton.setIconSize(QtCore.QSize(22, 22))
        self.resetMaskButton.setObjectName("resetMaskButton")
        self.gridLayout_13.addWidget(self.resetMaskButton, 0, 3, 1, 1)
        self.mask_lineEdit = QtWidgets.QLineEdit(self.tab_3)
        self.mask_lineEdit.setEnabled(False)
        self.mask_lineEdit.setInputMethodHints(QtCore.Qt.ImhUrlCharactersOnly)
        self.mask_lineEdit.setText("")
        self.mask_lineEdit.setObjectName("mask_lineEdit")
        self.gridLayout_13.addWidget(self.mask_lineEdit, 0, 1, 1, 2)
        self.verticalLayout_3.addLayout(self.gridLayout_13)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.vector_output_checkBox = QtWidgets.QCheckBox(self.tab_3)
        self.vector_output_checkBox.setObjectName("vector_output_checkBox")
        self.horizontalLayout_2.addWidget(self.vector_output_checkBox)
        self.report_checkBox = QtWidgets.QCheckBox(self.tab_3)
        self.report_checkBox.setObjectName("report_checkBox")
        self.horizontalLayout_2.addWidget(self.report_checkBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.alg_files_checkBox = QtWidgets.QCheckBox(self.tab_3)
        self.alg_files_checkBox.setObjectName("alg_files_checkBox")
        self.horizontalLayout_4.addWidget(self.alg_files_checkBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.gridLayout_41 = QtWidgets.QGridLayout()
        self.gridLayout_41.setObjectName("gridLayout_41")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_41.addItem(spacerItem8, 0, 0, 1, 1)
        self.button_classification = QtWidgets.QToolButton(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.button_classification.setFont(font)
        self.button_classification.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.button_classification.setStyleSheet("margin: 0px;padding: 0px;")
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_run.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_classification.setIcon(icon31)
        self.button_classification.setIconSize(QtCore.QSize(34, 34))
        self.button_classification.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.button_classification.setObjectName("button_classification")
        self.gridLayout_41.addWidget(self.button_classification, 0, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_41)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem9)
        self.gridLayout_9.addLayout(self.verticalLayout_3, 1, 1, 1, 1)
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_classification.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_dock.addTab(self.tab_3, icon32, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget_dock.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget_dock.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget_dock.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tabWidget_dock.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.tabWidget_dock.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.tabWidget_dock.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.tabWidget_dock.addTab(self.tab_10, "")
        self.gridLayout_2.addWidget(self.tabWidget_dock, 0, 0, 1, 1)
        DockClass.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockClass)
        self.tabWidget_dock.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DockClass)

    def retranslateUi(self, DockClass):
        _translate = QtCore.QCoreApplication.translate
        DockClass.setWindowTitle(_translate("DockClass", "SCP &Dock"))
        self.label_35.setText(_translate("DockClass", " News"))
        self.batch_toolButton.setToolTip(_translate("DockClass", "<html><head/><body><p>Batch</p></body></html>"))
        self.postprocessing_toolButton_2.setToolTip(_translate("DockClass", "<html><head/><body><p>Postprocessing</p></body></html>"))
        self.preprocessing_toolButton_2.setToolTip(_translate("DockClass", "<html><head/><body><p>Preprocessing</p></body></html>"))
        self.bandset_toolButton.setToolTip(_translate("DockClass", "<html><head/><body><p><span >Band set</span></p></body></html>"))
        self.bandcalc_toolButton_2.setToolTip(_translate("DockClass", "<html><head/><body><p><span >Band calc</span></p></body></html>"))
        self.download_images_toolButton_2.setToolTip(_translate("DockClass", "<html><head/><body><p>Download products</p></body></html>"))
        self.band_processing_toolButton.setToolTip(_translate("DockClass", "<html><head/><body><p>Band processing</p></body></html>"))
        self.basic_tools_toolButton.setToolTip(_translate("DockClass", "<html><head/><body><p>Basic tools</p></body></html>"))
        self.userguide_toolButton_2.setToolTip(_translate("DockClass", "<html><head/><body><p>User manual</p></body></html>"))
        self.userguide_toolButton_2.setText(_translate("DockClass", "User manual"))
        self.help_toolButton_2.setToolTip(_translate("DockClass", "<html><head/><body><p>Ask a question</p></body></html>"))
        self.help_toolButton_2.setText(_translate("DockClass", "Ask a question"))
        self.support_toolButton.setToolTip(_translate("DockClass", "<html><head/><body><p><span style=\" color:#ffffff;\">Support the SCP</span></p></body></html>"))
        self.support_toolButton.setText(_translate("DockClass", "Support the SCP"))
        self.tabWidget_dock.setTabText(self.tabWidget_dock.indexOf(self.tab), _translate("DockClass", "Home"))
        self.trainingFile_toolButton.setToolTip(_translate("DockClass", "<html><head/><body><p><span >Open a training input</span></p></body></html>"))
        self.button_new_input.setToolTip(_translate("DockClass", "<html><head/><body><p><span >Create a new training input</span></p></body></html>"))
        self.trainingFile_lineEdit.setToolTip(_translate("DockClass", "<html><head/><body><p>Input file path</p></body></html>"))
        self.undo_save_Button.setToolTip(_translate("DockClass", "<html><head/><body><p >Undo ROI save</p></body></html>"))
        self.undo_save_Button.setText(_translate("DockClass", "Import library"))
        self.save_input_checkBox.setToolTip(_translate("DockClass", "<html><head/><body><p>Automatically save training input when a ROI is saved in it</p></body></html>"))
        self.save_input_checkBox.setText(_translate("DockClass", "Autosave"))
        self.signature_checkBox.setToolTip(_translate("DockClass", "<html><head/><body><p>Add ROI spectral signature to signature list</p></body></html>"))
        self.signature_checkBox.setText(_translate("DockClass", "Signature"))
        self.button_Save_ROI.setToolTip(_translate("DockClass", "<html><head/><body><p >Save temporary ROI to training input</p></body></html>"))
        self.button_Save_ROI.setText(_translate("DockClass", "Import library"))
        self.merge_signature_toolButton.setToolTip(_translate("DockClass", "<html><head/><body><p >Merge highlighted spectral signatures obtaining the average signature</p></body></html>"))
        self.calculate_signature_toolButton.setToolTip(_translate("DockClass", "<html><head/><body><p>Calculate signatures for highlighted items</p></body></html>"))
        self.delete_Signature_Button.setToolTip(_translate("DockClass", "<html><head/><body><p>Delete highlighted items</p></body></html>"))
        self.delete_Signature_Button.setText(_translate("DockClass", "..."))
        self.signature_spectral_plot_toolButton.setToolTip(_translate("DockClass", "<html><head/><body><p >Add highlighted signatures to spectral signature plot</p></body></html>"))
        self.signature_spectral_plot_toolButton.setText(_translate("DockClass", "Plot"))
        self.scatterPlot_toolButton.setToolTip(_translate("DockClass", "<html><head/><body><p>Add highlighted items to scatter plot</p></body></html>"))
        self.scatterPlot_toolButton.setText(_translate("DockClass", "..."))
        self.import_library_toolButton.setToolTip(_translate("DockClass", "<html><head/><body><p>Import spectral signatures </p></body></html>"))
        self.import_library_toolButton.setText(_translate("DockClass", "Import library"))
        self.export_signature_list_toolButton.setToolTip(_translate("DockClass", "<html><head/><body><p >Export highlighted spectral signatures</p></body></html>\n"
""))
        self.export_signature_list_toolButton.setText(_translate("DockClass", "Import library"))
        self.signature_list_tableWidget.setSortingEnabled(True)
        item = self.signature_list_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("DockClass", "S"))
        item = self.signature_list_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("DockClass", "Type"))
        item = self.signature_list_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("DockClass", "MC ID"))
        item = self.signature_list_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("DockClass", "C ID"))
        item = self.signature_list_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("DockClass", "C Info"))
        item = self.signature_list_tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("DockClass", "Color"))
        self.label_41.setText(_translate("DockClass", "C Info"))
        self.ROI_Macroclass_ID_spin.setToolTip(_translate("DockClass", "<html><head/><body><p>The macroclass ID of the ROI signature</p></body></html>"))
        self.label_42.setText(_translate("DockClass", "C ID"))
        self.label_45.setText(_translate("DockClass", "MC Info"))
        self.label_44.setText(_translate("DockClass", "MC ID"))
        self.ROI_ID_spin.setToolTip(_translate("DockClass", "<html><head/><body><p>The class ID of the ROI signature</p></body></html>"))
        self.ROI_Class_line.setToolTip(_translate("DockClass", "<html><head/><body><p>The class name of the ROI signature</p></body></html>"))
        self.ROI_Class_line.setText(_translate("DockClass", "C 1"))
        self.ROI_Macroclass_line.setToolTip(_translate("DockClass", "<html><head/><body><p>The macroclass name of the ROI signature</p></body></html>"))
        self.ROI_Macroclass_line.setText(_translate("DockClass", "MC 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_ROI), _translate("DockClass", " ROI Signature list"))
        self.macroclass_color_tableWidget.setSortingEnabled(True)
        item = self.macroclass_color_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("DockClass", "MC ID"))
        item = self.macroclass_color_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("DockClass", "MC Info"))
        item = self.macroclass_color_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("DockClass", "Color"))
        self.add_MC_row_Button.setToolTip(_translate("DockClass", "<html><head/><body><p >Add row</p></body></html>"))
        self.add_MC_row_Button.setText(_translate("DockClass", "Plot"))
        self.delete_MC_row_Button.setToolTip(_translate("DockClass", "<html><head/><body><p >Delete row</p></body></html>"))
        self.delete_MC_row_Button.setText(_translate("DockClass", "Plot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_MC), _translate("DockClass", "Macroclass list"))
        self.rapid_ROI_checkBox.setToolTip(_translate("DockClass", "<html><head/><body><p>Calculate temporary ROI only on one band</p></body></html>"))
        self.rapid_ROI_checkBox.setText(_translate("DockClass", "Rapid ROI b."))
        self.rapidROI_band_spinBox.setToolTip(_translate("DockClass", "<html><head/><body><p>Band number</p></body></html>"))
        self.display_cursor_checkBox.setToolTip(_translate("DockClass", "<html><head/><body><p>Display a vegetation index value with the cursor</p></body></html>"))
        self.display_cursor_checkBox.setText(_translate("DockClass", "Display"))
        self.vegetation_index_comboBox.setToolTip(_translate("DockClass", "<html><head/><body><p>Select a vegetation index</p></body></html>"))
        self.vegetation_index_comboBox.setItemText(0, _translate("DockClass", "NDVI"))
        self.vegetation_index_comboBox.setItemText(1, _translate("DockClass", "EVI"))
        self.vegetation_index_comboBox.setItemText(2, _translate("DockClass", "Custom"))
        self.custom_index_lineEdit.setToolTip(_translate("DockClass", "<html><head/><body><p>Custom expression (e.g. bandset#b4 / bandset#b3 )</p></body></html>"))
        self.auto_refresh_ROI_radioButton.setToolTip(_translate("DockClass", "<html><head/><body><p>Automatically refresh the temporary ROI, as the parameters change</p></body></html>"))
        self.auto_refresh_ROI_radioButton.setText(_translate("DockClass", "A&uto-refresh ROI"))
        self.auto_calculate_ROI_signature_radioButton.setToolTip(_translate("DockClass", "<html><head/><body><p>Automatically calculate signature plot of temporary ROI</p></body></html>"))
        self.auto_calculate_ROI_signature_radioButton.setText(_translate("DockClass", "Auto-plot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_11), _translate("DockClass", " ROI options"))
        self.tabWidget_dock.setTabText(self.tabWidget_dock.indexOf(self.tab_2), _translate("DockClass", "Training input"))
        self.label_20.setText(_translate("DockClass", "Use"))
        self.macroclass_checkBox.setToolTip(_translate("DockClass", "<html><head/><body><p>Use the ID of macroclasses for the classification</p></body></html>"))
        self.macroclass_checkBox.setText(_translate("DockClass", "MC ID"))
        self.class_checkBox.setToolTip(_translate("DockClass", "<html><head/><body><p>Use the ID of classes for the classification</p></body></html>"))
        self.class_checkBox.setText(_translate("DockClass", "C ID"))
        self.algorithm_weight_button.setToolTip(_translate("DockClass", "<html><head/><body><p>Open tab Algorithm band weight</p></body></html>"))
        self.algorithm_weight_button.setText(_translate("DockClass", "W"))
        self.label_43.setText(_translate("DockClass", " Algorithm"))
        self.label_16.setText(_translate("DockClass", "Threshold"))
        self.algorithm_combo.setToolTip(_translate("DockClass", "<html><head/><body><p>Select a classification algorithm</p></body></html>"))
        self.algorithm_combo.setItemText(0, _translate("DockClass", "Minimum Distance"))
        self.algorithm_combo.setItemText(1, _translate("DockClass", "Maximum Likelihood"))
        self.algorithm_combo.setItemText(2, _translate("DockClass", "Spectral Angle Mapping"))
        self.alg_threshold_SpinBox.setToolTip(_translate("DockClass", "<html><head/><body><p>Set a classification threshold for all signatures</p></body></html>"))
        self.algorithm_threshold_button.setToolTip(_translate("DockClass", "<html><head/><body><p>Open tab Signature threshold</p></body></html>"))
        self.algorithm_threshold_button.setText(_translate("DockClass", "W"))
        self.label_21.setText(_translate("DockClass", "Use"))
        self.LC_signature_checkBox.setToolTip(_translate("DockClass", "<html><head/><body><p>If checked, the Land Cover Signature Classification is used</p></body></html>"))
        self.LC_signature_checkBox.setText(_translate("DockClass", "LCS"))
        self.LC_signature_button.setToolTip(_translate("DockClass", "<html><head/><body><p>Open tab LCS threshold</p></body></html>"))
        self.label_46.setText(_translate("DockClass", " Land Cover Signature Classification"))
        self.LCS_leave_unclassified_checkBox.setToolTip(_translate("DockClass", "<html><head/><body><p>If checked, the selected Algorithm is used only for class overlapping pixels of the Land Cover Signature Classification</p></body></html>"))
        self.LCS_leave_unclassified_checkBox.setText(_translate("DockClass", "only overlap"))
        self.LCS_class_algorithm_checkBox.setToolTip(_translate("DockClass", "<html><head/><body><p>If checked, the selected Algorithm is used for unclassified pixels of the Land Cover Signature Classification</p></body></html>"))
        self.LCS_class_algorithm_checkBox.setText(_translate("DockClass", "Algorithm"))
        self.label_47.setText(_translate("DockClass", " Classification output"))
        self.resetQmlButton.setToolTip(_translate("DockClass", "<html><head/><body><p><span >Reset</span></p></body></html>"))
        self.resetQmlButton.setText(_translate("DockClass", "Import library"))
        self.label_19.setText(_translate("DockClass", "Load qml style"))
        self.qml_Button.setToolTip(_translate("DockClass", "<html><head/><body><p><span >Select qml style</span></p></body></html>"))
        self.qml_Button.setText(_translate("DockClass", "Import library"))
        self.qml_lineEdit.setToolTip(_translate("DockClass", "<html><head/><body><p>Qml file path</p></body></html>"))
        self.mask_checkBox.setToolTip(_translate("DockClass", "<html><head/><body><p>Select an optional mask vector</p></body></html>"))
        self.mask_checkBox.setText(_translate("DockClass", "Apply mask"))
        self.resetMaskButton.setToolTip(_translate("DockClass", "<html><head/><body><p><span >Reset</span></p></body></html>"))
        self.resetMaskButton.setText(_translate("DockClass", "Import library"))
        self.mask_lineEdit.setToolTip(_translate("DockClass", "<html><head/><body><p>Path of the optional mask shapefile</p></body></html>"))
        self.vector_output_checkBox.setToolTip(_translate("DockClass", "<html><head/><body><p>Create a classification shapefile after the classification process</p></body></html>"))
        self.vector_output_checkBox.setText(_translate("DockClass", "Create vector"))
        self.report_checkBox.setToolTip(_translate("DockClass", "<html><head/><body><p>Calculate a classification report</p></body></html>"))
        self.report_checkBox.setText(_translate("DockClass", "Classification report"))
        self.alg_files_checkBox.setToolTip(_translate("DockClass", "<html><head/><body><p>If enabled, the rasters calculated by the classification algorithm (one per signature) are saved along with the classification</p></body></html>"))
        self.alg_files_checkBox.setText(_translate("DockClass", "Save algorithm files"))
        self.button_classification.setToolTip(_translate("DockClass", "<html><head/><body><p><span >Run</span></p></body></html>"))
        self.button_classification.setText(_translate("DockClass", "  RUN"))
        self.tabWidget_dock.setTabText(self.tabWidget_dock.indexOf(self.tab_3), _translate("DockClass", "Classification"))

from . import resources_rc
