# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_semiautomaticclassificationplugin_signature_plot.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SpectralSignaturePlot(object):
    def setupUi(self, SpectralSignaturePlot):
        SpectralSignaturePlot.setObjectName("SpectralSignaturePlot")
        SpectralSignaturePlot.resize(957, 564)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SpectralSignaturePlot.sizePolicy().hasHeightForWidth())
        SpectralSignaturePlot.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/semiautomaticclassificationplugin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SpectralSignaturePlot.setWindowIcon(icon)
        self.gridLayout_8 = QtWidgets.QGridLayout(SpectralSignaturePlot)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.signature_list_plot_tableWidget = QtWidgets.QTableWidget(SpectralSignaturePlot)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signature_list_plot_tableWidget.sizePolicy().hasHeightForWidth())
        self.signature_list_plot_tableWidget.setSizePolicy(sizePolicy)
        self.signature_list_plot_tableWidget.setMinimumSize(QtCore.QSize(0, 100))
        self.signature_list_plot_tableWidget.setMaximumSize(QtCore.QSize(16777215, 150))
        self.signature_list_plot_tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.SelectedClicked)
        self.signature_list_plot_tableWidget.setObjectName("signature_list_plot_tableWidget")
        self.signature_list_plot_tableWidget.setColumnCount(6)
        self.signature_list_plot_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.signature_list_plot_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.signature_list_plot_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.signature_list_plot_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.signature_list_plot_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.signature_list_plot_tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.signature_list_plot_tableWidget.setHorizontalHeaderItem(5, item)
        self.signature_list_plot_tableWidget.horizontalHeader().setDefaultSectionSize(50)
        self.signature_list_plot_tableWidget.horizontalHeader().setStretchLastSection(True)
        self.signature_list_plot_tableWidget.verticalHeader().setDefaultSectionSize(20)
        self.gridLayout_2.addWidget(self.signature_list_plot_tableWidget, 0, 0, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_2, 1, 0, 1, 2)
        self.frame = QtWidgets.QFrame(SpectralSignaturePlot)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.gridLayout_140 = QtWidgets.QGridLayout()
        self.gridLayout_140.setObjectName("gridLayout_140")
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.LCS_pointerButton_2 = QtWidgets.QToolButton(self.frame)
        self.LCS_pointerButton_2.setStyleSheet("margin: 0px;padding: 0px;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_LCS_threshold_set_tool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.LCS_pointerButton_2.setIcon(icon1)
        self.LCS_pointerButton_2.setIconSize(QtCore.QSize(22, 22))
        self.LCS_pointerButton_2.setObjectName("LCS_pointerButton_2")
        self.gridLayout_17.addWidget(self.LCS_pointerButton_2, 0, 2, 1, 1)
        self.label_90 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_90.sizePolicy().hasHeightForWidth())
        self.label_90.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setBold(False)
        font.setWeight(50)
        self.label_90.setFont(font)
        self.label_90.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_90.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_90.setObjectName("label_90")
        self.gridLayout_17.addWidget(self.label_90, 0, 1, 1, 1)
        self.gridLayout_144 = QtWidgets.QGridLayout()
        self.gridLayout_144.setObjectName("gridLayout_144")
        self.LCS_cut_checkBox_2 = QtWidgets.QCheckBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LCS_cut_checkBox_2.sizePolicy().hasHeightForWidth())
        self.LCS_cut_checkBox_2.setSizePolicy(sizePolicy)
        self.LCS_cut_checkBox_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.LCS_cut_checkBox_2.setIcon(icon2)
        self.LCS_cut_checkBox_2.setObjectName("LCS_cut_checkBox_2")
        self.gridLayout_144.addWidget(self.LCS_cut_checkBox_2, 1, 0, 1, 1)
        self.LCS_include_checkBox_2 = QtWidgets.QCheckBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LCS_include_checkBox_2.sizePolicy().hasHeightForWidth())
        self.LCS_include_checkBox_2.setSizePolicy(sizePolicy)
        self.LCS_include_checkBox_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.LCS_include_checkBox_2.setIcon(icon3)
        self.LCS_include_checkBox_2.setChecked(True)
        self.LCS_include_checkBox_2.setObjectName("LCS_include_checkBox_2")
        self.gridLayout_144.addWidget(self.LCS_include_checkBox_2, 0, 0, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_144, 0, 3, 1, 1)
        self.gridLayout_19 = QtWidgets.QGridLayout()
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.label_91 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_91.sizePolicy().hasHeightForWidth())
        self.label_91.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setBold(False)
        font.setWeight(50)
        self.label_91.setFont(font)
        self.label_91.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_91.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_91.setObjectName("label_91")
        self.gridLayout_19.addWidget(self.label_91, 0, 0, 1, 1)
        self.LCS_ROI_button_2 = QtWidgets.QToolButton(self.frame)
        self.LCS_ROI_button_2.setStyleSheet("margin: 0px;padding: 0px;")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_LCS_threshold_ROI_tool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.LCS_ROI_button_2.setIcon(icon4)
        self.LCS_ROI_button_2.setIconSize(QtCore.QSize(22, 22))
        self.LCS_ROI_button_2.setObjectName("LCS_ROI_button_2")
        self.gridLayout_19.addWidget(self.LCS_ROI_button_2, 0, 1, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_19, 0, 0, 1, 1)
        self.gridLayout_140.addLayout(self.gridLayout_17, 2, 0, 1, 2)
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_26 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("background-color : qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #535353, stop:1 #a6a6a6); color : white")
        self.label_26.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_26.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout_14.addWidget(self.label_26, 0, 0, 1, 3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_20 = QtWidgets.QGridLayout()
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.set_min_max_Button = QtWidgets.QToolButton(self.frame)
        self.set_min_max_Button.setStyleSheet("margin: 0px;padding: 0px;")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_enter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.set_min_max_Button.setIcon(icon5)
        self.set_min_max_Button.setIconSize(QtCore.QSize(22, 22))
        self.set_min_max_Button.setObjectName("set_min_max_Button")
        self.gridLayout_20.addWidget(self.set_min_max_Button, 0, 1, 1, 1)
        self.label_102 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_102.sizePolicy().hasHeightForWidth())
        self.label_102.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setBold(False)
        font.setWeight(50)
        self.label_102.setFont(font)
        self.label_102.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_102.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_102.setObjectName("label_102")
        self.gridLayout_20.addWidget(self.label_102, 0, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_20)
        self.label_101 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setBold(False)
        font.setWeight(50)
        self.label_101.setFont(font)
        self.label_101.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_101.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_101.setObjectName("label_101")
        self.horizontalLayout_2.addWidget(self.label_101)
        self.multiplicative_threshold_doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.multiplicative_threshold_doubleSpinBox_2.sizePolicy().hasHeightForWidth())
        self.multiplicative_threshold_doubleSpinBox_2.setSizePolicy(sizePolicy)
        self.multiplicative_threshold_doubleSpinBox_2.setDecimals(1)
        self.multiplicative_threshold_doubleSpinBox_2.setMaximum(10000.0)
        self.multiplicative_threshold_doubleSpinBox_2.setProperty("value", 1.0)
        self.multiplicative_threshold_doubleSpinBox_2.setObjectName("multiplicative_threshold_doubleSpinBox_2")
        self.horizontalLayout_2.addWidget(self.multiplicative_threshold_doubleSpinBox_2)
        self.automatic_threshold_pushButton_2 = QtWidgets.QToolButton(self.frame)
        self.automatic_threshold_pushButton_2.setStyleSheet("margin: 0px;padding: 0px;")
        self.automatic_threshold_pushButton_2.setIcon(icon5)
        self.automatic_threshold_pushButton_2.setIconSize(QtCore.QSize(22, 22))
        self.automatic_threshold_pushButton_2.setObjectName("automatic_threshold_pushButton_2")
        self.horizontalLayout_2.addWidget(self.automatic_threshold_pushButton_2)
        self.undo_threshold_Button = QtWidgets.QToolButton(self.frame)
        self.undo_threshold_Button.setEnabled(False)
        self.undo_threshold_Button.setStyleSheet("margin: 0px;padding: 0px;")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_undo_lcs_threshold.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.undo_threshold_Button.setIcon(icon6)
        self.undo_threshold_Button.setIconSize(QtCore.QSize(22, 22))
        self.undo_threshold_Button.setObjectName("undo_threshold_Button")
        self.horizontalLayout_2.addWidget(self.undo_threshold_Button)
        self.gridLayout_14.addLayout(self.horizontalLayout_2, 1, 0, 1, 3)
        self.gridLayout_140.addLayout(self.gridLayout_14, 1, 0, 1, 2)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.remove_Signature_Button = QtWidgets.QToolButton(self.frame)
        self.remove_Signature_Button.setStyleSheet("margin: 0px;padding: 0px;")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.remove_Signature_Button.setIcon(icon7)
        self.remove_Signature_Button.setIconSize(QtCore.QSize(22, 22))
        self.remove_Signature_Button.setObjectName("remove_Signature_Button")
        self.gridLayout_4.addWidget(self.remove_Signature_Button, 0, 0, 1, 1)
        self.add_signature_list_pushButton = QtWidgets.QToolButton(self.frame)
        self.add_signature_list_pushButton.setStyleSheet("margin: 0px;padding: 0px;")
        self.add_signature_list_pushButton.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_save_plot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_signature_list_pushButton.setIcon(icon8)
        self.add_signature_list_pushButton.setIconSize(QtCore.QSize(22, 22))
        self.add_signature_list_pushButton.setObjectName("add_signature_list_pushButton")
        self.gridLayout_4.addWidget(self.add_signature_list_pushButton, 0, 1, 1, 1)
        self.calculate_spectral_distance_Button = QtWidgets.QToolButton(self.frame)
        self.calculate_spectral_distance_Button.setStyleSheet("margin: 0px;padding: 0px;")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_calculate_spectral_distances.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.calculate_spectral_distance_Button.setIcon(icon9)
        self.calculate_spectral_distance_Button.setIconSize(QtCore.QSize(22, 22))
        self.calculate_spectral_distance_Button.setObjectName("calculate_spectral_distance_Button")
        self.gridLayout_4.addWidget(self.calculate_spectral_distance_Button, 0, 2, 1, 1)
        self.gridLayout_140.addLayout(self.gridLayout_4, 0, 0, 1, 2)
        self.gridLayout_18.addLayout(self.gridLayout_140, 0, 0, 1, 1)
        self.gridLayout_16.addWidget(self.frame, 1, 2, 1, 1)
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_25 = QtWidgets.QLabel(SpectralSignaturePlot)
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("background-color : qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #535353, stop:1 #a6a6a6); color : white")
        self.label_25.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_25.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_15.addWidget(self.label_25, 0, 0, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_15, 0, 0, 1, 3)
        self.gridLayout_5.addLayout(self.gridLayout_16, 1, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tabWidget = QtWidgets.QTabWidget(SpectralSignaturePlot)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Sig_Widget = SigWidget2(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Sig_Widget.sizePolicy().hasHeightForWidth())
        self.Sig_Widget.setSizePolicy(sizePolicy)
        self.Sig_Widget.setObjectName("Sig_Widget")
        self.gridLayout_3.addWidget(self.Sig_Widget, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.band_lines_checkBox = QtWidgets.QCheckBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.band_lines_checkBox.sizePolicy().hasHeightForWidth())
        self.band_lines_checkBox.setSizePolicy(sizePolicy)
        self.band_lines_checkBox.setChecked(True)
        self.band_lines_checkBox.setObjectName("band_lines_checkBox")
        self.gridLayout_7.addWidget(self.band_lines_checkBox, 0, 5, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 0, 8, 1, 1)
        self.plot_text_spinBox = QtWidgets.QSpinBox(self.tab)
        self.plot_text_spinBox.setMinimumSize(QtCore.QSize(50, 0))
        self.plot_text_spinBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.plot_text_spinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.plot_text_spinBox.setMinimum(1)
        self.plot_text_spinBox.setMaximum(100)
        self.plot_text_spinBox.setProperty("value", 15)
        self.plot_text_spinBox.setObjectName("plot_text_spinBox")
        self.gridLayout_7.addWidget(self.plot_text_spinBox, 0, 9, 1, 1)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.value_label = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setBold(True)
        font.setWeight(75)
        self.value_label.setFont(font)
        self.value_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.value_label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.value_label.setObjectName("value_label")
        self.gridLayout_13.addWidget(self.value_label, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem, 0, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_13, 0, 11, 1, 1)
        self.value_range_pushButton = QtWidgets.QToolButton(self.tab)
        self.value_range_pushButton.setStyleSheet("margin: 0px;padding: 0px;")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_sign_edit_range.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.value_range_pushButton.setIcon(icon10)
        self.value_range_pushButton.setIconSize(QtCore.QSize(22, 22))
        self.value_range_pushButton.setObjectName("value_range_pushButton")
        self.gridLayout_7.addWidget(self.value_range_pushButton, 0, 2, 1, 1)
        self.fitToAxes_pushButton = QtWidgets.QToolButton(self.tab)
        self.fitToAxes_pushButton.setStyleSheet("margin: 0px;padding: 0px;")
        self.fitToAxes_pushButton.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_fit_plot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fitToAxes_pushButton.setIcon(icon11)
        self.fitToAxes_pushButton.setIconSize(QtCore.QSize(22, 22))
        self.fitToAxes_pushButton.setObjectName("fitToAxes_pushButton")
        self.gridLayout_7.addWidget(self.fitToAxes_pushButton, 0, 0, 1, 1)
        self.save_plot_pushButton = QtWidgets.QToolButton(self.tab)
        self.save_plot_pushButton.setStyleSheet("margin: 0px;padding: 0px;")
        self.save_plot_pushButton.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_save_plot_image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_plot_pushButton.setIcon(icon12)
        self.save_plot_pushButton.setIconSize(QtCore.QSize(22, 22))
        self.save_plot_pushButton.setObjectName("save_plot_pushButton")
        self.gridLayout_7.addWidget(self.save_plot_pushButton, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem1, 0, 4, 1, 1)
        self.sigma_checkBox = QtWidgets.QCheckBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sigma_checkBox.sizePolicy().hasHeightForWidth())
        self.sigma_checkBox.setSizePolicy(sizePolicy)
        self.sigma_checkBox.setChecked(True)
        self.sigma_checkBox.setObjectName("sigma_checkBox")
        self.gridLayout_7.addWidget(self.sigma_checkBox, 0, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem2, 0, 10, 1, 1)
        self.grid_checkBox = QtWidgets.QCheckBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grid_checkBox.sizePolicy().hasHeightForWidth())
        self.grid_checkBox.setSizePolicy(sizePolicy)
        self.grid_checkBox.setChecked(True)
        self.grid_checkBox.setObjectName("grid_checkBox")
        self.gridLayout_7.addWidget(self.grid_checkBox, 0, 6, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem3, 0, 7, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_7, 1, 0, 1, 1)
        self.Sig_Widget.raise_()
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_sign_tool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon13, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.value_textBrowser = QtWidgets.QTextBrowser(self.tab_2)
        self.value_textBrowser.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.value_textBrowser.setObjectName("value_textBrowser")
        self.gridLayout_9.addWidget(self.value_textBrowser, 0, 0, 1, 1)
        self.gridLayout_21.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_accuracy_tool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_2, icon14, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.distance_textBrowser = QtWidgets.QTextBrowser(self.tab_3)
        self.distance_textBrowser.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.distance_textBrowser.setObjectName("distance_textBrowser")
        self.gridLayout_11.addWidget(self.distance_textBrowser, 0, 0, 1, 1)
        self.gridLayout_22.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, icon9, "")
        self.gridLayout_6.addWidget(self.tabWidget, 0, 1, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_6, 1, 0, 1, 1)

        self.retranslateUi(SpectralSignaturePlot)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SpectralSignaturePlot)

    def retranslateUi(self, SpectralSignaturePlot):
        _translate = QtCore.QCoreApplication.translate
        SpectralSignaturePlot.setWindowTitle(_translate("SpectralSignaturePlot", "SCP: Spectral Signature Plot"))
        self.signature_list_plot_tableWidget.setSortingEnabled(True)
        item = self.signature_list_plot_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("SpectralSignaturePlot", "S"))
        item = self.signature_list_plot_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("SpectralSignaturePlot", "MC ID"))
        item = self.signature_list_plot_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("SpectralSignaturePlot", "MC Info"))
        item = self.signature_list_plot_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("SpectralSignaturePlot", "C ID"))
        item = self.signature_list_plot_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("SpectralSignaturePlot", "C Info"))
        item = self.signature_list_plot_tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("SpectralSignaturePlot", "Color"))
        self.LCS_pointerButton_2.setToolTip(_translate("SpectralSignaturePlot", "<html><head/><body><p>Activate pointer for setting thresholds from pixel</p></body></html>"))
        self.label_90.setText(_translate("SpectralSignaturePlot", "From pixel"))
        self.LCS_cut_checkBox_2.setToolTip(_translate("SpectralSignaturePlot", "<html><head/><body><p>If checked, signature threshold is reduced to exclude pixel signature</p></body></html>"))
        self.LCS_include_checkBox_2.setToolTip(_translate("SpectralSignaturePlot", "<html><head/><body><p>If checked, signature threshold is extended to include pixel signature</p></body></html>"))
        self.label_91.setText(_translate("SpectralSignaturePlot", "From ROI"))
        self.LCS_ROI_button_2.setToolTip(_translate("SpectralSignaturePlot", "<html><head/><body><p>Set thresholds from temporary ROI</p></body></html>"))
        self.label_26.setText(_translate("SpectralSignaturePlot", "Automatic  thresholds"))
        self.set_min_max_Button.setToolTip(_translate("SpectralSignaturePlot", "<html><head/><body><p>Set automatic threshold Min Max</p></body></html>"))
        self.label_102.setText(_translate("SpectralSignaturePlot", "Min Max"))
        self.label_101.setText(_translate("SpectralSignaturePlot", "σ *"))
        self.multiplicative_threshold_doubleSpinBox_2.setToolTip(_translate("SpectralSignaturePlot", "<html><head/><body><p>Set a value that will be multiplied by standard deviation</p></body></html>"))
        self.automatic_threshold_pushButton_2.setToolTip(_translate("SpectralSignaturePlot", "<html><head/><body><p>Set automatic threshold σ</p></body></html>"))
        self.undo_threshold_Button.setToolTip(_translate("SpectralSignaturePlot", "<html><head/><body><p>Undo thresholds</p></body></html>"))
        self.undo_threshold_Button.setText(_translate("SpectralSignaturePlot", "Import library"))
        self.remove_Signature_Button.setToolTip(_translate("SpectralSignaturePlot", "<html><head/><body><p >Delete row</p></body></html>"))
        self.remove_Signature_Button.setText(_translate("SpectralSignaturePlot", "Plot"))
        self.add_signature_list_pushButton.setToolTip(_translate("SpectralSignaturePlot", "<html><head/><body><p>Add highlighted spectral signatures to signature list</p></body></html>"))
        self.calculate_spectral_distance_Button.setToolTip(_translate("SpectralSignaturePlot", "<html><head/><body><p>Calculate spectral distances</p></body></html>"))
        self.calculate_spectral_distance_Button.setText(_translate("SpectralSignaturePlot", "Plot"))
        self.label_25.setText(_translate("SpectralSignaturePlot", " Signature list"))
        self.band_lines_checkBox.setToolTip(_translate("SpectralSignaturePlot", "<html><head/><body><p>Plot the value range (standard deviation or defined minimum and maximum) for each signature</p></body></html>"))
        self.band_lines_checkBox.setText(_translate("SpectralSignaturePlot", "Band lines"))
        self.label_8.setText(_translate("SpectralSignaturePlot", "Max characters"))
        self.plot_text_spinBox.setToolTip(_translate("SpectralSignaturePlot", "<html><head/><body><p align=\"justify\">Text lenght of names in the spectral plot legend</p></body></html>"))
        self.value_label.setText(_translate("SpectralSignaturePlot", "x=0.000000 y=0.000000"))
        self.value_range_pushButton.setToolTip(_translate("SpectralSignaturePlot", "<html><head/><body><p>Change value range interactively in the plot</p></body></html>"))
        self.fitToAxes_pushButton.setToolTip(_translate("SpectralSignaturePlot", "<html><head/><body><p>Automatically fit the plot to data</p></body></html>"))
        self.save_plot_pushButton.setToolTip(_translate("SpectralSignaturePlot", "<html><head/><body><p>Save the plot to file (jpg, png, pdf)</p></body></html>"))
        self.sigma_checkBox.setToolTip(_translate("SpectralSignaturePlot", "<html><head/><body><p>Plot the value range (standard deviation or defined minimum and maximum) for each signature</p></body></html>"))
        self.sigma_checkBox.setText(_translate("SpectralSignaturePlot", "Plot value range"))
        self.grid_checkBox.setToolTip(_translate("SpectralSignaturePlot", "<html><head/><body><p>Plot the value range (standard deviation or defined minimum and maximum) for each signature</p></body></html>"))
        self.grid_checkBox.setText(_translate("SpectralSignaturePlot", "Grid"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("SpectralSignaturePlot", "Plot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("SpectralSignaturePlot", "Signature details"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("SpectralSignaturePlot", "Spectral distances"))

from .sigwidget2 import SigWidget2
from . import resources_rc
