# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_semiautomaticclassificationplugin_dock_class.ui'
#
# Created: Wed Sep 14 18:54:25 2016
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DockClass(object):
    def setupUi(self, DockClass):
        DockClass.setObjectName(_fromUtf8("DockClass"))
        DockClass.resize(344, 585)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DockClass.sizePolicy().hasHeightForWidth())
        DockClass.setSizePolicy(sizePolicy)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout_46 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_46.setObjectName(_fromUtf8("gridLayout_46"))
        self.SCP_toolBox = QtGui.QToolBox(self.dockWidgetContents)
        self.SCP_toolBox.setObjectName(_fromUtf8("SCP_toolBox"))
        self.page_5 = QtGui.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 320, 498))
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.gridLayout_9 = QtGui.QGridLayout(self.page_5)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.frame_3 = QtGui.QFrame(self.page_5)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.gridLayout_20 = QtGui.QGridLayout(self.frame_3)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.gridLayout_36 = QtGui.QGridLayout()
        self.gridLayout_36.setObjectName(_fromUtf8("gridLayout_36"))
        self.gridLayout_40 = QtGui.QGridLayout()
        self.gridLayout_40.setObjectName(_fromUtf8("gridLayout_40"))
        self.bandcalc_toolButton_2 = QtGui.QToolButton(self.frame_3)
        self.bandcalc_toolButton_2.setStyleSheet(_fromUtf8("margin: 0px;padding: 0px;"))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_bandcalc_tool.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bandcalc_toolButton_2.setIcon(icon)
        self.bandcalc_toolButton_2.setIconSize(QtCore.QSize(22, 22))
        self.bandcalc_toolButton_2.setObjectName(_fromUtf8("bandcalc_toolButton_2"))
        self.gridLayout_40.addWidget(self.bandcalc_toolButton_2, 0, 5, 1, 1)
        self.ROItools_toolButton_2 = QtGui.QToolButton(self.frame_3)
        self.ROItools_toolButton_2.setStyleSheet(_fromUtf8("margin: 0px;padding: 0px;"))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_roi_tool.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ROItools_toolButton_2.setIcon(icon1)
        self.ROItools_toolButton_2.setIconSize(QtCore.QSize(22, 22))
        self.ROItools_toolButton_2.setObjectName(_fromUtf8("ROItools_toolButton_2"))
        self.gridLayout_40.addWidget(self.ROItools_toolButton_2, 0, 2, 1, 1)
        self.preprocessing_toolButton_2 = QtGui.QToolButton(self.frame_3)
        self.preprocessing_toolButton_2.setStyleSheet(_fromUtf8("margin: 0px;padding: 0px;"))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_class_tool.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.preprocessing_toolButton_2.setIcon(icon2)
        self.preprocessing_toolButton_2.setIconSize(QtCore.QSize(22, 22))
        self.preprocessing_toolButton_2.setObjectName(_fromUtf8("preprocessing_toolButton_2"))
        self.gridLayout_40.addWidget(self.preprocessing_toolButton_2, 0, 3, 1, 1)
        self.settings_toolButton_2 = QtGui.QToolButton(self.frame_3)
        self.settings_toolButton_2.setStyleSheet(_fromUtf8("margin: 0px;padding: 0px;"))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_settings_tool.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settings_toolButton_2.setIcon(icon3)
        self.settings_toolButton_2.setIconSize(QtCore.QSize(22, 22))
        self.settings_toolButton_2.setObjectName(_fromUtf8("settings_toolButton_2"))
        self.gridLayout_40.addWidget(self.settings_toolButton_2, 0, 7, 1, 1)
        self.postprocessing_toolButton_2 = QtGui.QToolButton(self.frame_3)
        self.postprocessing_toolButton_2.setStyleSheet(_fromUtf8("margin: 0px;padding: 0px;"))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_post_process.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.postprocessing_toolButton_2.setIcon(icon4)
        self.postprocessing_toolButton_2.setIconSize(QtCore.QSize(22, 22))
        self.postprocessing_toolButton_2.setObjectName(_fromUtf8("postprocessing_toolButton_2"))
        self.gridLayout_40.addWidget(self.postprocessing_toolButton_2, 0, 4, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_40.addItem(spacerItem, 0, 10, 1, 1)
        self.userguide_toolButton_2 = QtGui.QToolButton(self.frame_3)
        self.userguide_toolButton_2.setStyleSheet(_fromUtf8("margin: 0px;padding: 0px;"))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/semiautomaticclassificationplugin/icons/guide.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.userguide_toolButton_2.setIcon(icon5)
        self.userguide_toolButton_2.setIconSize(QtCore.QSize(22, 22))
        self.userguide_toolButton_2.setObjectName(_fromUtf8("userguide_toolButton_2"))
        self.gridLayout_40.addWidget(self.userguide_toolButton_2, 0, 8, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_40.addItem(spacerItem1, 0, 0, 1, 1)
        self.help_toolButton_2 = QtGui.QToolButton(self.frame_3)
        self.help_toolButton_2.setStyleSheet(_fromUtf8("margin: 0px;padding: 0px;"))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/semiautomaticclassificationplugin/icons/help.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.help_toolButton_2.setIcon(icon6)
        self.help_toolButton_2.setIconSize(QtCore.QSize(22, 22))
        self.help_toolButton_2.setObjectName(_fromUtf8("help_toolButton_2"))
        self.gridLayout_40.addWidget(self.help_toolButton_2, 0, 9, 1, 1)
        self.download_images_toolButton_2 = QtGui.QToolButton(self.frame_3)
        self.download_images_toolButton_2.setStyleSheet(_fromUtf8("margin: 0px;padding: 0px;"))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_download_arrow.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.download_images_toolButton_2.setIcon(icon7)
        self.download_images_toolButton_2.setIconSize(QtCore.QSize(22, 22))
        self.download_images_toolButton_2.setObjectName(_fromUtf8("download_images_toolButton_2"))
        self.gridLayout_40.addWidget(self.download_images_toolButton_2, 0, 1, 1, 1)
        self.gridLayout_36.addLayout(self.gridLayout_40, 0, 0, 1, 1)
        self.gridLayout_20.addLayout(self.gridLayout_36, 1, 0, 1, 1)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gridLayout_18 = QtGui.QGridLayout()
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.label_33 = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet(_fromUtf8("background-color : qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #535353, stop:1 #a6a6a6); color : white"))
        self.label_33.setFrameShape(QtGui.QFrame.Panel)
        self.label_33.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_18.addWidget(self.label_33, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_18, 1, 0, 1, 1)
        self.gridLayout_19 = QtGui.QGridLayout()
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.trainingFile_lineEdit = QtGui.QLineEdit(self.frame_3)
        self.trainingFile_lineEdit.setEnabled(False)
        self.trainingFile_lineEdit.setObjectName(_fromUtf8("trainingFile_lineEdit"))
        self.gridLayout_19.addWidget(self.trainingFile_lineEdit, 0, 2, 1, 1)
        self.trainingFile_toolButton = QtGui.QToolButton(self.frame_3)
        self.trainingFile_toolButton.setStyleSheet(_fromUtf8("margin: 0px;padding: 0px;"))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_open_file.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.trainingFile_toolButton.setIcon(icon8)
        self.trainingFile_toolButton.setIconSize(QtCore.QSize(22, 22))
        self.trainingFile_toolButton.setObjectName(_fromUtf8("trainingFile_toolButton"))
        self.gridLayout_19.addWidget(self.trainingFile_toolButton, 0, 0, 1, 1)
        self.button_new_input = QtGui.QToolButton(self.frame_3)
        self.button_new_input.setStyleSheet(_fromUtf8("margin: 0px;padding: 0px;"))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_new_file.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_new_input.setIcon(icon9)
        self.button_new_input.setIconSize(QtCore.QSize(22, 22))
        self.button_new_input.setObjectName(_fromUtf8("button_new_input"))
        self.gridLayout_19.addWidget(self.button_new_input, 0, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_19, 2, 0, 1, 1)
        self.gridLayout_35 = QtGui.QGridLayout()
        self.gridLayout_35.setObjectName(_fromUtf8("gridLayout_35"))
        self.toolButton_reload = QtGui.QToolButton(self.frame_3)
        self.toolButton_reload.setStyleSheet(_fromUtf8("margin: 0px;padding: 0px;"))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_reload.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_reload.setIcon(icon10)
        self.toolButton_reload.setIconSize(QtCore.QSize(22, 22))
        self.toolButton_reload.setObjectName(_fromUtf8("toolButton_reload"))
        self.gridLayout_35.addWidget(self.toolButton_reload, 1, 3, 1, 1)
        self.bandset_toolButton = QtGui.QToolButton(self.frame_3)
        self.bandset_toolButton.setStyleSheet(_fromUtf8("margin: 0px;padding: 0px;"))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_bandset_tool.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bandset_toolButton.setIcon(icon11)
        self.bandset_toolButton.setIconSize(QtCore.QSize(22, 22))
        self.bandset_toolButton.setObjectName(_fromUtf8("bandset_toolButton"))
        self.gridLayout_35.addWidget(self.bandset_toolButton, 1, 1, 1, 1)
        self.raster_name_combo = QtGui.QComboBox(self.frame_3)
        self.raster_name_combo.setObjectName(_fromUtf8("raster_name_combo"))
        self.gridLayout_35.addWidget(self.raster_name_combo, 1, 2, 1, 1)
        self.input_raster_toolButton = QtGui.QToolButton(self.frame_3)
        self.input_raster_toolButton.setStyleSheet(_fromUtf8("margin: 0px;padding: 0px;"))
        self.input_raster_toolButton.setIcon(icon8)
        self.input_raster_toolButton.setIconSize(QtCore.QSize(22, 22))
        self.input_raster_toolButton.setObjectName(_fromUtf8("input_raster_toolButton"))
        self.gridLayout_35.addWidget(self.input_raster_toolButton, 1, 0, 1, 1)
        self.label_34 = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet(_fromUtf8("background-color : qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #535353, stop:1 #a6a6a6); color : white"))
        self.label_34.setFrameShape(QtGui.QFrame.Panel)
        self.label_34.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_35.addWidget(self.label_34, 0, 0, 1, 4)
        self.gridLayout_6.addLayout(self.gridLayout_35, 0, 0, 1, 1)
        self.gridLayout_20.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.gridLayout_12 = QtGui.QGridLayout()
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.main_textBrowser = QtGui.QTextBrowser(self.frame_3)
        self.main_textBrowser.setHtml(_fromUtf8("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.main_textBrowser.setOpenExternalLinks(True)
        self.main_textBrowser.setObjectName(_fromUtf8("main_textBrowser"))
        self.gridLayout_12.addWidget(self.main_textBrowser, 1, 0, 1, 1)
        self.label_35 = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet(_fromUtf8("background-color : qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #535353, stop:1 #a6a6a6); color : white"))
        self.label_35.setFrameShape(QtGui.QFrame.Panel)
        self.label_35.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_12.addWidget(self.label_35, 0, 0, 1, 1)
        self.gridLayout_20.addLayout(self.gridLayout_12, 2, 0, 1, 1)
        self.gridLayout_9.addWidget(self.frame_3, 0, 0, 1, 1)
        self.SCP_toolBox.addItem(self.page_5, _fromUtf8(""))
        self.page_7 = QtGui.QWidget()
        self.page_7.setGeometry(QtCore.QRect(0, 0, 320, 498))
        self.page_7.setObjectName(_fromUtf8("page_7"))
        self.gridLayout_3 = QtGui.QGridLayout(self.page_7)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.frame_4 = QtGui.QFrame(self.page_7)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.gridLayout_21 = QtGui.QGridLayout(self.frame_4)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_39 = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet(_fromUtf8("background-color : qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #535353, stop:1 #a6a6a6); color : white"))
        self.label_39.setFrameShape(QtGui.QFrame.Panel)
        self.label_39.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_39.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout.addWidget(self.label_39, 0, 0, 1, 1)
        self.signature_list_tableWidget = QtGui.QTableWidget(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signature_list_tableWidget.sizePolicy().hasHeightForWidth())
        self.signature_list_tableWidget.setSizePolicy(sizePolicy)
        self.signature_list_tableWidget.setMinimumSize(QtCore.QSize(0, 150))
        self.signature_list_tableWidget.setEditTriggers(QtGui.QAbstractItemView.SelectedClicked)
        self.signature_list_tableWidget.setObjectName(_fromUtf8("signature_list_tableWidget"))
        self.signature_list_tableWidget.setColumnCount(6)
        self.signature_list_tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.signature_list_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.signature_list_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.signature_list_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.signature_list_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.signature_list_tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.signature_list_tableWidget.setHorizontalHeaderItem(5, item)
        self.signature_list_tableWidget.horizontalHeader().setDefaultSectionSize(50)
        self.signature_list_tableWidget.horizontalHeader().setStretchLastSection(False)
        self.signature_list_tableWidget.verticalHeader().setDefaultSectionSize(20)
        self.gridLayout.addWidget(self.signature_list_tableWidget, 1, 0, 1, 1)
        self.gridLayout_21.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_16 = QtGui.QGridLayout()
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.gridLayout_28 = QtGui.QGridLayout()
        self.gridLayout_28.setObjectName(_fromUtf8("gridLayout_28"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_28.addItem(spacerItem2, 0, 3, 1, 1)
        self.scatterPlot_toolButton = QtGui.QToolButton(self.frame_4)
        self.scatterPlot_toolButton.setStyleSheet(_fromUtf8("margin: 0px;padding: 0px;"))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_scatter_tool.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.scatterPlot_toolButton.setIcon(icon12)
        self.scatterPlot_toolButton.setIconSize(QtCore.QSize(22, 22))
        self.scatterPlot_toolButton.setObjectName(_fromUtf8("scatterPlot_toolButton"))
        self.gridLayout_28.addWidget(self.scatterPlot_toolButton, 0, 5, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_28.addItem(spacerItem3, 0, 6, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.import_library_toolButton = QtGui.QToolButton(self.frame_4)
        self.import_library_toolButton.setStyleSheet(_fromUtf8("margin: 0px;padding: 0px;"))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_import_spectral_library.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.import_library_toolButton.setIcon(icon13)
        self.import_library_toolButton.setIconSize(QtCore.QSize(22, 22))
        self.import_library_toolButton.setObjectName(_fromUtf8("import_library_toolButton"))
        self.gridLayout_2.addWidget(self.import_library_toolButton, 0, 0, 1, 1)
        self.export_signature_list_toolButton = QtGui.QToolButton(self.frame_4)
        self.export_signature_list_toolButton.setStyleSheet(_fromUtf8("margin: 0px;padding: 0px;"))
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_export_spectral_library.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.export_signature_list_toolButton.setIcon(icon14)
        self.export_signature_list_toolButton.setIconSize(QtCore.QSize(22, 22))
        self.export_signature_list_toolButton.setObjectName(_fromUtf8("export_signature_list_toolButton"))
        self.gridLayout_2.addWidget(self.export_signature_list_toolButton, 0, 1, 1, 1)
        self.gridLayout_28.addLayout(self.gridLayout_2, 0, 7, 1, 1)
        self.delete_Signature_Button = QtGui.QToolButton(self.frame_4)
        self.delete_Signature_Button.setStyleSheet(_fromUtf8("margin: 0px;padding: 0px;"))
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_delete_signature.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_Signature_Button.setIcon(icon15)
        self.delete_Signature_Button.setIconSize(QtCore.QSize(22, 22))
        self.delete_Signature_Button.setObjectName(_fromUtf8("delete_Signature_Button"))
        self.gridLayout_28.addWidget(self.delete_Signature_Button, 0, 0, 1, 1)
        self.calculate_signature_toolButton = QtGui.QToolButton(self.frame_4)
        self.calculate_signature_toolButton.setStyleSheet(_fromUtf8("margin: 0px;padding: 0px;"))
        self.calculate_signature_toolButton.setText(_fromUtf8(""))
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_calculate_signature.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.calculate_signature_toolButton.setIcon(icon16)
        self.calculate_signature_toolButton.setIconSize(QtCore.QSize(22, 22))
        self.calculate_signature_toolButton.setObjectName(_fromUtf8("calculate_signature_toolButton"))
        self.gridLayout_28.addWidget(self.calculate_signature_toolButton, 0, 2, 1, 1)
        self.merge_signature_toolButton = QtGui.QToolButton(self.frame_4)
        self.merge_signature_toolButton.setStyleSheet(_fromUtf8("margin: 0px;padding: 0px;"))
        self.merge_signature_toolButton.setText(_fromUtf8(""))
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_merge_sign_tool.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.merge_signature_toolButton.setIcon(icon17)
        self.merge_signature_toolButton.setIconSize(QtCore.QSize(22, 22))
        self.merge_signature_toolButton.setObjectName(_fromUtf8("merge_signature_toolButton"))
        self.gridLayout_28.addWidget(self.merge_signature_toolButton, 0, 1, 1, 1)
        self.signature_spectral_plot_toolButton = QtGui.QToolButton(self.frame_4)
        self.signature_spectral_plot_toolButton.setStyleSheet(_fromUtf8("margin: 0px;padding: 0px;"))
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_sign_tool.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.signature_spectral_plot_toolButton.setIcon(icon18)
        self.signature_spectral_plot_toolButton.setIconSize(QtCore.QSize(22, 22))
        self.signature_spectral_plot_toolButton.setObjectName(_fromUtf8("signature_spectral_plot_toolButton"))
        self.gridLayout_28.addWidget(self.signature_spectral_plot_toolButton, 0, 4, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_28, 0, 1, 1, 5)
        self.gridLayout_21.addLayout(self.gridLayout_16, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_4, 0, 0, 1, 1)
        self.gridLayout_17 = QtGui.QGridLayout()
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.toolBox = QtGui.QToolBox(self.page_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setFrameShape(QtGui.QFrame.StyledPanel)
        self.toolBox.setFrameShadow(QtGui.QFrame.Raised)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page_6 = QtGui.QWidget()
        self.page_6.setGeometry(QtCore.QRect(0, 0, 283, 216))
        self.page_6.setObjectName(_fromUtf8("page_6"))
        self.gridLayout_26 = QtGui.QGridLayout(self.page_6)
        self.gridLayout_26.setObjectName(_fromUtf8("gridLayout_26"))
        self.frame = QtGui.QFrame(self.page_6)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_14 = QtGui.QGridLayout(self.frame)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.gridLayout_29 = QtGui.QGridLayout()
        self.gridLayout_29.setObjectName(_fromUtf8("gridLayout_29"))
        self.display_cursor_checkBox = QtGui.QCheckBox(self.frame)
        self.display_cursor_checkBox.setChecked(True)
        self.display_cursor_checkBox.setObjectName(_fromUtf8("display_cursor_checkBox"))
        self.gridLayout_29.addWidget(self.display_cursor_checkBox, 0, 0, 1, 1)
        self.vegetation_index_comboBox = QtGui.QComboBox(self.frame)
        self.vegetation_index_comboBox.setObjectName(_fromUtf8("vegetation_index_comboBox"))
        self.vegetation_index_comboBox.addItem(_fromUtf8(""))
        self.vegetation_index_comboBox.addItem(_fromUtf8(""))
        self.vegetation_index_comboBox.addItem(_fromUtf8(""))
        self.gridLayout_29.addWidget(self.vegetation_index_comboBox, 0, 1, 1, 1)
        self.custom_index_lineEdit = QtGui.QLineEdit(self.frame)
        self.custom_index_lineEdit.setObjectName(_fromUtf8("custom_index_lineEdit"))
        self.gridLayout_29.addWidget(self.custom_index_lineEdit, 0, 2, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_29, 1, 0, 1, 1)
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.gridLayout_27 = QtGui.QGridLayout()
        self.gridLayout_27.setVerticalSpacing(4)
        self.gridLayout_27.setObjectName(_fromUtf8("gridLayout_27"))
        self.ROI_Class_line = QtGui.QLineEdit(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ROI_Class_line.sizePolicy().hasHeightForWidth())
        self.ROI_Class_line.setSizePolicy(sizePolicy)
        self.ROI_Class_line.setMaxLength(80)
        self.ROI_Class_line.setObjectName(_fromUtf8("ROI_Class_line"))
        self.gridLayout_27.addWidget(self.ROI_Class_line, 5, 4, 1, 1)
        self.ROI_Macroclass_ID_spin = QtGui.QSpinBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ROI_Macroclass_ID_spin.sizePolicy().hasHeightForWidth())
        self.ROI_Macroclass_ID_spin.setSizePolicy(sizePolicy)
        self.ROI_Macroclass_ID_spin.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ROI_Macroclass_ID_spin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ROI_Macroclass_ID_spin.setMinimum(0)
        self.ROI_Macroclass_ID_spin.setMaximum(9999)
        self.ROI_Macroclass_ID_spin.setProperty("value", 1)
        self.ROI_Macroclass_ID_spin.setObjectName(_fromUtf8("ROI_Macroclass_ID_spin"))
        self.gridLayout_27.addWidget(self.ROI_Macroclass_ID_spin, 3, 1, 1, 2)
        self.ROI_Macroclass_line = QtGui.QLineEdit(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ROI_Macroclass_line.sizePolicy().hasHeightForWidth())
        self.ROI_Macroclass_line.setSizePolicy(sizePolicy)
        self.ROI_Macroclass_line.setMaxLength(80)
        self.ROI_Macroclass_line.setObjectName(_fromUtf8("ROI_Macroclass_line"))
        self.gridLayout_27.addWidget(self.ROI_Macroclass_line, 3, 4, 1, 1)
        self.label_42 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_42.sizePolicy().hasHeightForWidth())
        self.label_42.setSizePolicy(sizePolicy)
        self.label_42.setMaximumSize(QtCore.QSize(89, 16777215))
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_27.addWidget(self.label_42, 5, 0, 1, 1)
        self.label_41 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_41.sizePolicy().hasHeightForWidth())
        self.label_41.setSizePolicy(sizePolicy)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_27.addWidget(self.label_41, 5, 3, 1, 1)
        self.label_45 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_45.sizePolicy().hasHeightForWidth())
        self.label_45.setSizePolicy(sizePolicy)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_27.addWidget(self.label_45, 3, 3, 1, 1)
        self.label_44 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_44.sizePolicy().hasHeightForWidth())
        self.label_44.setSizePolicy(sizePolicy)
        self.label_44.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_27.addWidget(self.label_44, 3, 0, 1, 1)
        self.ROI_ID_spin = QtGui.QSpinBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ROI_ID_spin.sizePolicy().hasHeightForWidth())
        self.ROI_ID_spin.setSizePolicy(sizePolicy)
        self.ROI_ID_spin.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ROI_ID_spin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ROI_ID_spin.setMinimum(0)
        self.ROI_ID_spin.setMaximum(9999)
        self.ROI_ID_spin.setProperty("value", 1)
        self.ROI_ID_spin.setObjectName(_fromUtf8("ROI_ID_spin"))
        self.gridLayout_27.addWidget(self.ROI_ID_spin, 5, 1, 1, 2)
        self.gridLayout_10.addLayout(self.gridLayout_27, 0, 0, 1, 5)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.undo_save_Button = QtGui.QToolButton(self.frame)
        self.undo_save_Button.setStyleSheet(_fromUtf8("margin: 0px;padding: 0px;"))
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_undo_save_roi.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.undo_save_Button.setIcon(icon19)
        self.undo_save_Button.setIconSize(QtCore.QSize(22, 22))
        self.undo_save_Button.setObjectName(_fromUtf8("undo_save_Button"))
        self.horizontalLayout.addWidget(self.undo_save_Button)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.signature_checkBox = QtGui.QCheckBox(self.frame)
        self.signature_checkBox.setChecked(True)
        self.signature_checkBox.setObjectName(_fromUtf8("signature_checkBox"))
        self.horizontalLayout.addWidget(self.signature_checkBox)
        self.button_Save_ROI = QtGui.QToolButton(self.frame)
        self.button_Save_ROI.setStyleSheet(_fromUtf8("margin: 0px;padding: 0px;"))
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_save_roi.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_Save_ROI.setIcon(icon20)
        self.button_Save_ROI.setIconSize(QtCore.QSize(22, 22))
        self.button_Save_ROI.setObjectName(_fromUtf8("button_Save_ROI"))
        self.horizontalLayout.addWidget(self.button_Save_ROI)
        self.gridLayout_10.addLayout(self.horizontalLayout, 1, 0, 1, 5)
        self.gridLayout_14.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.gridLayout_34 = QtGui.QGridLayout()
        self.gridLayout_34.setObjectName(_fromUtf8("gridLayout_34"))
        self.auto_refresh_ROI_radioButton = QtGui.QRadioButton(self.frame)
        self.auto_refresh_ROI_radioButton.setAutoExclusive(False)
        self.auto_refresh_ROI_radioButton.setObjectName(_fromUtf8("auto_refresh_ROI_radioButton"))
        self.gridLayout_34.addWidget(self.auto_refresh_ROI_radioButton, 1, 0, 1, 1)
        self.gridLayout_38 = QtGui.QGridLayout()
        self.gridLayout_38.setObjectName(_fromUtf8("gridLayout_38"))
        self.rapidROI_band_spinBox = QtGui.QSpinBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rapidROI_band_spinBox.sizePolicy().hasHeightForWidth())
        self.rapidROI_band_spinBox.setSizePolicy(sizePolicy)
        self.rapidROI_band_spinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rapidROI_band_spinBox.setMinimum(1)
        self.rapidROI_band_spinBox.setMaximum(10000)
        self.rapidROI_band_spinBox.setProperty("value", 1)
        self.rapidROI_band_spinBox.setObjectName(_fromUtf8("rapidROI_band_spinBox"))
        self.gridLayout_38.addWidget(self.rapidROI_band_spinBox, 0, 1, 1, 1)
        self.rapid_ROI_checkBox = QtGui.QCheckBox(self.frame)
        self.rapid_ROI_checkBox.setObjectName(_fromUtf8("rapid_ROI_checkBox"))
        self.gridLayout_38.addWidget(self.rapid_ROI_checkBox, 0, 0, 1, 1)
        self.gridLayout_34.addLayout(self.gridLayout_38, 0, 0, 1, 1)
        self.auto_calculate_ROI_signature_radioButton = QtGui.QRadioButton(self.frame)
        self.auto_calculate_ROI_signature_radioButton.setAutoExclusive(False)
        self.auto_calculate_ROI_signature_radioButton.setObjectName(_fromUtf8("auto_calculate_ROI_signature_radioButton"))
        self.gridLayout_34.addWidget(self.auto_calculate_ROI_signature_radioButton, 2, 0, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_34, 2, 0, 1, 1)
        self.gridLayout_26.addWidget(self.frame, 0, 0, 1, 1)
        self.toolBox.addItem(self.page_6, _fromUtf8(""))
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 177, 158))
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.gridLayout_24 = QtGui.QGridLayout(self.page_3)
        self.gridLayout_24.setObjectName(_fromUtf8("gridLayout_24"))
        self.frame_5 = QtGui.QFrame(self.page_3)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.gridLayout_32 = QtGui.QGridLayout(self.frame_5)
        self.gridLayout_32.setObjectName(_fromUtf8("gridLayout_32"))
        self.gridLayout_23 = QtGui.QGridLayout()
        self.gridLayout_23.setObjectName(_fromUtf8("gridLayout_23"))
        self.gridLayout_44 = QtGui.QGridLayout()
        self.gridLayout_44.setObjectName(_fromUtf8("gridLayout_44"))
        self.label_40 = QtGui.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet(_fromUtf8("background-color : qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #535353, stop:1 #a6a6a6); color : white"))
        self.label_40.setFrameShape(QtGui.QFrame.Panel)
        self.label_40.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_40.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_44.addWidget(self.label_40, 0, 0, 1, 1)
        self.gridLayout_23.addLayout(self.gridLayout_44, 2, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.add_MC_row_Button = QtGui.QToolButton(self.frame_5)
        self.add_MC_row_Button.setStyleSheet(_fromUtf8("margin: 0px;padding: 0px;"))
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_MC_row_Button.setIcon(icon21)
        self.add_MC_row_Button.setIconSize(QtCore.QSize(22, 22))
        self.add_MC_row_Button.setObjectName(_fromUtf8("add_MC_row_Button"))
        self.verticalLayout_2.addWidget(self.add_MC_row_Button)
        self.delete_MC_row_Button = QtGui.QToolButton(self.frame_5)
        self.delete_MC_row_Button.setStyleSheet(_fromUtf8("margin: 0px;padding: 0px;"))
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_remove.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_MC_row_Button.setIcon(icon22)
        self.delete_MC_row_Button.setIconSize(QtCore.QSize(22, 22))
        self.delete_MC_row_Button.setObjectName(_fromUtf8("delete_MC_row_Button"))
        self.verticalLayout_2.addWidget(self.delete_MC_row_Button)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.gridLayout_23.addLayout(self.verticalLayout_2, 1, 1, 1, 1)
        self.macroclass_color_tableWidget = QtGui.QTableWidget(self.frame_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.macroclass_color_tableWidget.sizePolicy().hasHeightForWidth())
        self.macroclass_color_tableWidget.setSizePolicy(sizePolicy)
        self.macroclass_color_tableWidget.setEditTriggers(QtGui.QAbstractItemView.SelectedClicked)
        self.macroclass_color_tableWidget.setObjectName(_fromUtf8("macroclass_color_tableWidget"))
        self.macroclass_color_tableWidget.setColumnCount(3)
        self.macroclass_color_tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.macroclass_color_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.macroclass_color_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.macroclass_color_tableWidget.setHorizontalHeaderItem(2, item)
        self.macroclass_color_tableWidget.horizontalHeader().setDefaultSectionSize(50)
        self.macroclass_color_tableWidget.verticalHeader().setDefaultSectionSize(20)
        self.gridLayout_23.addWidget(self.macroclass_color_tableWidget, 1, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_23.addItem(spacerItem7, 0, 0, 1, 1)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setSpacing(4)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.qml_lineEdit = QtGui.QLineEdit(self.frame_5)
        self.qml_lineEdit.setEnabled(False)
        self.qml_lineEdit.setObjectName(_fromUtf8("qml_lineEdit"))
        self.gridLayout_7.addWidget(self.qml_lineEdit, 0, 2, 1, 1)
        self.resetQmlButton = QtGui.QToolButton(self.frame_5)
        self.resetQmlButton.setStyleSheet(_fromUtf8("margin: 0px;padding: 0px;"))
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_reset.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.resetQmlButton.setIcon(icon23)
        self.resetQmlButton.setIconSize(QtCore.QSize(22, 22))
        self.resetQmlButton.setObjectName(_fromUtf8("resetQmlButton"))
        self.gridLayout_7.addWidget(self.resetQmlButton, 0, 4, 1, 1)
        self.label_19 = QtGui.QLabel(self.frame_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_7.addWidget(self.label_19, 0, 0, 1, 1)
        self.qml_Button = QtGui.QToolButton(self.frame_5)
        self.qml_Button.setStyleSheet(_fromUtf8("margin: 0px;padding: 0px;"))
        self.qml_Button.setIcon(icon8)
        self.qml_Button.setIconSize(QtCore.QSize(22, 22))
        self.qml_Button.setObjectName(_fromUtf8("qml_Button"))
        self.gridLayout_7.addWidget(self.qml_Button, 0, 3, 1, 1)
        self.gridLayout_23.addLayout(self.gridLayout_7, 3, 0, 1, 2)
        self.gridLayout_32.addLayout(self.gridLayout_23, 0, 0, 1, 1)
        self.gridLayout_24.addWidget(self.frame_5, 0, 1, 1, 1)
        self.toolBox.addItem(self.page_3, _fromUtf8(""))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 326, 163))
        self.page.setObjectName(_fromUtf8("page"))
        self.gridLayout_39 = QtGui.QGridLayout(self.page)
        self.gridLayout_39.setObjectName(_fromUtf8("gridLayout_39"))
        self.frame_2 = QtGui.QFrame(self.page)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout_15 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem8, 1, 0, 1, 1)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setSpacing(4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gridLayout_33 = QtGui.QGridLayout()
        self.gridLayout_33.setObjectName(_fromUtf8("gridLayout_33"))
        self.label_16 = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_33.addWidget(self.label_16, 2, 1, 1, 1)
        self.algorithm_combo = QtGui.QComboBox(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.algorithm_combo.sizePolicy().hasHeightForWidth())
        self.algorithm_combo.setSizePolicy(sizePolicy)
        self.algorithm_combo.setMinimumSize(QtCore.QSize(100, 0))
        self.algorithm_combo.setObjectName(_fromUtf8("algorithm_combo"))
        self.algorithm_combo.addItem(_fromUtf8(""))
        self.algorithm_combo.addItem(_fromUtf8(""))
        self.algorithm_combo.addItem(_fromUtf8(""))
        self.gridLayout_33.addWidget(self.algorithm_combo, 2, 0, 1, 1)
        self.alg_threshold_SpinBox = QtGui.QDoubleSpinBox(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alg_threshold_SpinBox.sizePolicy().hasHeightForWidth())
        self.alg_threshold_SpinBox.setSizePolicy(sizePolicy)
        self.alg_threshold_SpinBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.alg_threshold_SpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.alg_threshold_SpinBox.setDecimals(4)
        self.alg_threshold_SpinBox.setMaximum(10000.0)
        self.alg_threshold_SpinBox.setObjectName(_fromUtf8("alg_threshold_SpinBox"))
        self.gridLayout_33.addWidget(self.alg_threshold_SpinBox, 2, 2, 1, 1)
        self.algorithm_threshold_button = QtGui.QToolButton(self.frame_2)
        self.algorithm_threshold_button.setStyleSheet(_fromUtf8("margin: 0px;padding: 0px;"))
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_threshold_tool.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.algorithm_threshold_button.setIcon(icon24)
        self.algorithm_threshold_button.setIconSize(QtCore.QSize(22, 22))
        self.algorithm_threshold_button.setObjectName(_fromUtf8("algorithm_threshold_button"))
        self.gridLayout_33.addWidget(self.algorithm_threshold_button, 2, 3, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_20 = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_3.addWidget(self.label_20)
        self.macroclass_checkBox = QtGui.QCheckBox(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.macroclass_checkBox.sizePolicy().hasHeightForWidth())
        self.macroclass_checkBox.setSizePolicy(sizePolicy)
        self.macroclass_checkBox.setObjectName(_fromUtf8("macroclass_checkBox"))
        self.horizontalLayout_3.addWidget(self.macroclass_checkBox)
        self.class_checkBox = QtGui.QCheckBox(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.class_checkBox.sizePolicy().hasHeightForWidth())
        self.class_checkBox.setSizePolicy(sizePolicy)
        self.class_checkBox.setObjectName(_fromUtf8("class_checkBox"))
        self.horizontalLayout_3.addWidget(self.class_checkBox)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.algorithm_weight_button = QtGui.QToolButton(self.frame_2)
        self.algorithm_weight_button.setStyleSheet(_fromUtf8("margin: 0px;padding: 0px;"))
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_weight_tool.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.algorithm_weight_button.setIcon(icon25)
        self.algorithm_weight_button.setIconSize(QtCore.QSize(22, 22))
        self.algorithm_weight_button.setObjectName(_fromUtf8("algorithm_weight_button"))
        self.horizontalLayout_3.addWidget(self.algorithm_weight_button)
        self.gridLayout_33.addLayout(self.horizontalLayout_3, 0, 0, 1, 4)
        self.label_43 = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setStyleSheet(_fromUtf8("background-color : qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #535353, stop:1 #a6a6a6); color : white"))
        self.label_43.setFrameShape(QtGui.QFrame.Panel)
        self.label_43.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_43.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_33.addWidget(self.label_43, 1, 0, 1, 4)
        self.gridLayout_5.addLayout(self.gridLayout_33, 0, 0, 1, 2)
        self.gridLayout_43 = QtGui.QGridLayout()
        self.gridLayout_43.setObjectName(_fromUtf8("gridLayout_43"))
        self.label_21 = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_43.addWidget(self.label_21, 1, 0, 1, 1)
        self.LC_signature_checkBox = QtGui.QCheckBox(self.frame_2)
        self.LC_signature_checkBox.setObjectName(_fromUtf8("LC_signature_checkBox"))
        self.gridLayout_43.addWidget(self.LC_signature_checkBox, 1, 1, 1, 1)
        self.LCS_class_algorithm_checkBox = QtGui.QCheckBox(self.frame_2)
        self.LCS_class_algorithm_checkBox.setObjectName(_fromUtf8("LCS_class_algorithm_checkBox"))
        self.gridLayout_43.addWidget(self.LCS_class_algorithm_checkBox, 1, 2, 1, 1)
        self.LCS_leave_unclassified_checkBox = QtGui.QCheckBox(self.frame_2)
        self.LCS_leave_unclassified_checkBox.setObjectName(_fromUtf8("LCS_leave_unclassified_checkBox"))
        self.gridLayout_43.addWidget(self.LCS_leave_unclassified_checkBox, 1, 3, 1, 1)
        self.LC_signature_button = QtGui.QToolButton(self.frame_2)
        self.LC_signature_button.setStyleSheet(_fromUtf8("margin: 0px;padding: 0px;"))
        self.LC_signature_button.setText(_fromUtf8(""))
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_LCS_threshold_tool.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.LC_signature_button.setIcon(icon26)
        self.LC_signature_button.setIconSize(QtCore.QSize(22, 22))
        self.LC_signature_button.setObjectName(_fromUtf8("LC_signature_button"))
        self.gridLayout_43.addWidget(self.LC_signature_button, 1, 4, 1, 1)
        self.label_46 = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setBold(True)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setStyleSheet(_fromUtf8("background-color : qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #535353, stop:1 #a6a6a6); color : white"))
        self.label_46.setFrameShape(QtGui.QFrame.Panel)
        self.label_46.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_46.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_43.addWidget(self.label_46, 0, 0, 1, 5)
        self.gridLayout_5.addLayout(self.gridLayout_43, 1, 0, 1, 2)
        self.gridLayout_4.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridLayout_39.addWidget(self.frame_2, 0, 1, 1, 1)
        self.toolBox.addItem(self.page, _fromUtf8(""))
        self.page_4 = QtGui.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 291, 158))
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.gridLayout_25 = QtGui.QGridLayout(self.page_4)
        self.gridLayout_25.setObjectName(_fromUtf8("gridLayout_25"))
        self.frame_7 = QtGui.QFrame(self.page_4)
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.gridLayout_42 = QtGui.QGridLayout(self.frame_7)
        self.gridLayout_42.setObjectName(_fromUtf8("gridLayout_42"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setSpacing(4)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.gridLayout_13 = QtGui.QGridLayout()
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.mask_checkBox = QtGui.QCheckBox(self.frame_7)
        self.mask_checkBox.setObjectName(_fromUtf8("mask_checkBox"))
        self.gridLayout_13.addWidget(self.mask_checkBox, 0, 0, 1, 1)
        self.mask_lineEdit = QtGui.QLineEdit(self.frame_7)
        self.mask_lineEdit.setEnabled(False)
        self.mask_lineEdit.setInputMethodHints(QtCore.Qt.ImhUrlCharactersOnly)
        self.mask_lineEdit.setText(_fromUtf8(""))
        self.mask_lineEdit.setObjectName(_fromUtf8("mask_lineEdit"))
        self.gridLayout_13.addWidget(self.mask_lineEdit, 0, 2, 1, 1)
        self.resetMaskButton = QtGui.QToolButton(self.frame_7)
        self.resetMaskButton.setStyleSheet(_fromUtf8("margin: 0px;padding: 0px;"))
        self.resetMaskButton.setIcon(icon23)
        self.resetMaskButton.setIconSize(QtCore.QSize(22, 22))
        self.resetMaskButton.setObjectName(_fromUtf8("resetMaskButton"))
        self.gridLayout_13.addWidget(self.resetMaskButton, 0, 3, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_13, 2, 0, 1, 2)
        self.verticalLayout_3.addLayout(self.gridLayout_11)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.vector_output_checkBox = QtGui.QCheckBox(self.frame_7)
        self.vector_output_checkBox.setObjectName(_fromUtf8("vector_output_checkBox"))
        self.horizontalLayout_2.addWidget(self.vector_output_checkBox)
        self.report_checkBox = QtGui.QCheckBox(self.frame_7)
        self.report_checkBox.setObjectName(_fromUtf8("report_checkBox"))
        self.horizontalLayout_2.addWidget(self.report_checkBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.alg_files_checkBox = QtGui.QCheckBox(self.frame_7)
        self.alg_files_checkBox.setObjectName(_fromUtf8("alg_files_checkBox"))
        self.horizontalLayout_4.addWidget(self.alg_files_checkBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.gridLayout_41 = QtGui.QGridLayout()
        self.gridLayout_41.setObjectName(_fromUtf8("gridLayout_41"))
        self.button_classification = QtGui.QToolButton(self.frame_7)
        self.button_classification.setStyleSheet(_fromUtf8("margin: 0px;padding: 0px;"))
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_run.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_classification.setIcon(icon27)
        self.button_classification.setIconSize(QtCore.QSize(34, 34))
        self.button_classification.setObjectName(_fromUtf8("button_classification"))
        self.gridLayout_41.addWidget(self.button_classification, 0, 1, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_41.addItem(spacerItem10, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_41)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem11)
        self.gridLayout_42.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.gridLayout_25.addWidget(self.frame_7, 0, 0, 1, 1)
        self.toolBox.addItem(self.page_4, _fromUtf8(""))
        self.gridLayout_17.addWidget(self.toolBox, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_17, 1, 0, 1, 1)
        self.SCP_toolBox.addItem(self.page_7, _fromUtf8(""))
        self.gridLayout_46.addWidget(self.SCP_toolBox, 0, 0, 1, 1)
        DockClass.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockClass)
        self.SCP_toolBox.setCurrentIndex(0)
        self.SCP_toolBox.layout().setSpacing(0)
        self.toolBox.setCurrentIndex(0)
        self.toolBox.layout().setSpacing(-1)
        QtCore.QMetaObject.connectSlotsByName(DockClass)

    def retranslateUi(self, DockClass):
        DockClass.setWindowTitle(_translate("DockClass", "SCP Dock", None))
        self.bandcalc_toolButton_2.setToolTip(_translate("DockClass", "<html><head/><body><p><span >Band calc</span></p></body></html>", None))
        self.ROItools_toolButton_2.setToolTip(_translate("DockClass", "<html><head/><body><p><span >Tools</span></p></body></html>", None))
        self.preprocessing_toolButton_2.setToolTip(_translate("DockClass", "<html><head/><body><p>Preprocessing</p></body></html>", None))
        self.settings_toolButton_2.setToolTip(_translate("DockClass", "<html><head/><body><p><span >Settings</span></p></body></html>", None))
        self.postprocessing_toolButton_2.setToolTip(_translate("DockClass", "<html><head/><body><p>Postprocessing</p></body></html>", None))
        self.userguide_toolButton_2.setToolTip(_translate("DockClass", "<html><head/><body><p>User manual</p></body></html>", None))
        self.help_toolButton_2.setToolTip(_translate("DockClass", "<html><head/><body><p><span >Online help</span></p></body></html>", None))
        self.download_images_toolButton_2.setToolTip(_translate("DockClass", "<html><head/><body><p><span >Download images</span></p></body></html>", None))
        self.label_33.setText(_translate("DockClass", " Training input", None))
        self.trainingFile_lineEdit.setToolTip(_translate("DockClass", "<html><head/><body><p>Input file path</p></body></html>", None))
        self.trainingFile_toolButton.setToolTip(_translate("DockClass", "<html><head/><body><p><span >Open a training input</span></p></body></html>", None))
        self.button_new_input.setToolTip(_translate("DockClass", "<html><head/><body><p><span >Create a new training input</span></p></body></html>", None))
        self.toolButton_reload.setToolTip(_translate("DockClass", "<html><head/><body><p >Refresh list</p></body></html>", None))
        self.toolButton_reload.setText(_translate("DockClass", "Plot", None))
        self.bandset_toolButton.setToolTip(_translate("DockClass", "<html><head/><body><p><span >Band set</span></p></body></html>", None))
        self.raster_name_combo.setToolTip(_translate("DockClass", "<html><head/><body><p>Select an image</p></body></html>", None))
        self.input_raster_toolButton.setToolTip(_translate("DockClass", "<html><head/><body><p>Open a file</p></body></html>", None))
        self.label_34.setText(_translate("DockClass", " Input image", None))
        self.label_35.setText(_translate("DockClass", " SCP news", None))
        self.SCP_toolBox.setItemText(self.SCP_toolBox.indexOf(self.page_5), _translate("DockClass", "SCP input", None))
        self.label_39.setText(_translate("DockClass", " ROI Signature list", None))
        self.signature_list_tableWidget.setSortingEnabled(True)
        item = self.signature_list_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("DockClass", "S", None))
        item = self.signature_list_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("DockClass", "Type", None))
        item = self.signature_list_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("DockClass", "MC ID", None))
        item = self.signature_list_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("DockClass", "C ID", None))
        item = self.signature_list_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("DockClass", "C Info", None))
        item = self.signature_list_tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("DockClass", "Color", None))
        self.scatterPlot_toolButton.setToolTip(_translate("DockClass", "<html><head/><body><p>Add highlighted items to scatter plot</p></body></html>", None))
        self.scatterPlot_toolButton.setText(_translate("DockClass", "...", None))
        self.import_library_toolButton.setToolTip(_translate("DockClass", "<html><head/><body><p>Import spectral signatures </p></body></html>", None))
        self.import_library_toolButton.setText(_translate("DockClass", "Import library", None))
        self.export_signature_list_toolButton.setToolTip(_translate("DockClass", "<html><head/><body><p >Export highlighted spectral signatures</p></body></html>\n"
"", None))
        self.export_signature_list_toolButton.setText(_translate("DockClass", "Import library", None))
        self.delete_Signature_Button.setToolTip(_translate("DockClass", "<html><head/><body><p>Delete highlighted items</p></body></html>", None))
        self.delete_Signature_Button.setText(_translate("DockClass", "...", None))
        self.calculate_signature_toolButton.setToolTip(_translate("DockClass", "<html><head/><body><p>Calculate signatures for highlighted items</p></body></html>", None))
        self.merge_signature_toolButton.setToolTip(_translate("DockClass", "<html><head/><body><p >Merge highlighted spectral signatures obtaining the average signature</p></body></html>", None))
        self.signature_spectral_plot_toolButton.setToolTip(_translate("DockClass", "<html><head/><body><p >Add highlighted signatures to spectral signature plot</p></body></html>", None))
        self.signature_spectral_plot_toolButton.setText(_translate("DockClass", "Plot", None))
        self.display_cursor_checkBox.setToolTip(_translate("DockClass", "<html><head/><body><p>Display a vegetation index value with the cursor</p></body></html>", None))
        self.display_cursor_checkBox.setText(_translate("DockClass", "Display", None))
        self.vegetation_index_comboBox.setToolTip(_translate("DockClass", "<html><head/><body><p>Select a vegetation index</p></body></html>", None))
        self.vegetation_index_comboBox.setItemText(0, _translate("DockClass", "NDVI", None))
        self.vegetation_index_comboBox.setItemText(1, _translate("DockClass", "EVI", None))
        self.vegetation_index_comboBox.setItemText(2, _translate("DockClass", "Custom", None))
        self.custom_index_lineEdit.setToolTip(_translate("DockClass", "<html><head/><body><p>Custom expression (e.g. bandset#b4 / bandset#b3 )</p></body></html>", None))
        self.ROI_Class_line.setToolTip(_translate("DockClass", "<html><head/><body><p>The class name of the ROI signature</p></body></html>", None))
        self.ROI_Class_line.setText(_translate("DockClass", "C 1", None))
        self.ROI_Macroclass_ID_spin.setToolTip(_translate("DockClass", "<html><head/><body><p>The macroclass ID of the ROI signature</p></body></html>", None))
        self.ROI_Macroclass_line.setToolTip(_translate("DockClass", "<html><head/><body><p>The macroclass name of the ROI signature</p></body></html>", None))
        self.ROI_Macroclass_line.setText(_translate("DockClass", "MC 1", None))
        self.label_42.setText(_translate("DockClass", "C ID", None))
        self.label_41.setText(_translate("DockClass", "C Info", None))
        self.label_45.setText(_translate("DockClass", "MC Info", None))
        self.label_44.setText(_translate("DockClass", "MC ID", None))
        self.ROI_ID_spin.setToolTip(_translate("DockClass", "<html><head/><body><p>The class ID of the ROI signature</p></body></html>", None))
        self.undo_save_Button.setToolTip(_translate("DockClass", "<html><head/><body><p >Undo ROI save</p></body></html>", None))
        self.undo_save_Button.setText(_translate("DockClass", "Import library", None))
        self.signature_checkBox.setToolTip(_translate("DockClass", "<html><head/><body><p>Add ROI spectral signature to signature list</p></body></html>", None))
        self.signature_checkBox.setText(_translate("DockClass", "Calculate sig.", None))
        self.button_Save_ROI.setToolTip(_translate("DockClass", "<html><head/><body><p >Save temporary ROI to training input</p></body></html>", None))
        self.button_Save_ROI.setText(_translate("DockClass", "Import library", None))
        self.auto_refresh_ROI_radioButton.setToolTip(_translate("DockClass", "<html><head/><body><p>Automatically refresh the temporary ROI, as the parameters change</p></body></html>", None))
        self.auto_refresh_ROI_radioButton.setText(_translate("DockClass", "Automatic refresh ROI", None))
        self.rapidROI_band_spinBox.setToolTip(_translate("DockClass", "<html><head/><body><p>Band number</p></body></html>", None))
        self.rapid_ROI_checkBox.setToolTip(_translate("DockClass", "<html><head/><body><p>Calculate temporary ROI only on one band</p></body></html>", None))
        self.rapid_ROI_checkBox.setText(_translate("DockClass", "Rapid ROI band", None))
        self.auto_calculate_ROI_signature_radioButton.setToolTip(_translate("DockClass", "<html><head/><body><p>Automatically calculate signature plot of temporary ROI</p></body></html>", None))
        self.auto_calculate_ROI_signature_radioButton.setText(_translate("DockClass", "Automatic  plot", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_6), _translate("DockClass", "ROI creation", None))
        self.label_40.setText(_translate("DockClass", "Classification style", None))
        self.add_MC_row_Button.setToolTip(_translate("DockClass", "<html><head/><body><p >Add row</p></body></html>", None))
        self.add_MC_row_Button.setText(_translate("DockClass", "Plot", None))
        self.delete_MC_row_Button.setToolTip(_translate("DockClass", "<html><head/><body><p >Delete row</p></body></html>", None))
        self.delete_MC_row_Button.setText(_translate("DockClass", "Plot", None))
        self.macroclass_color_tableWidget.setSortingEnabled(True)
        item = self.macroclass_color_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("DockClass", "MC ID", None))
        item = self.macroclass_color_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("DockClass", "MC Info", None))
        item = self.macroclass_color_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("DockClass", "Color", None))
        self.qml_lineEdit.setToolTip(_translate("DockClass", "<html><head/><body><p>Qml file path</p></body></html>", None))
        self.resetQmlButton.setToolTip(_translate("DockClass", "<html><head/><body><p><span >Reset</span></p></body></html>", None))
        self.resetQmlButton.setText(_translate("DockClass", "Import library", None))
        self.label_19.setText(_translate("DockClass", "Load qml", None))
        self.qml_Button.setToolTip(_translate("DockClass", "<html><head/><body><p><span >Select qml style</span></p></body></html>", None))
        self.qml_Button.setText(_translate("DockClass", "Import library", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("DockClass", " Macroclasses", None))
        self.label_16.setText(_translate("DockClass", "Threshold", None))
        self.algorithm_combo.setToolTip(_translate("DockClass", "<html><head/><body><p>Select a classification algorithm</p></body></html>", None))
        self.algorithm_combo.setItemText(0, _translate("DockClass", "Minimum Distance", None))
        self.algorithm_combo.setItemText(1, _translate("DockClass", "Maximum Likelihood", None))
        self.algorithm_combo.setItemText(2, _translate("DockClass", "Spectral Angle Mapping", None))
        self.alg_threshold_SpinBox.setToolTip(_translate("DockClass", "<html><head/><body><p>Set a classification threshold for all signatures</p></body></html>", None))
        self.algorithm_threshold_button.setToolTip(_translate("DockClass", "<html><head/><body><p>Open tab Signature threshold</p></body></html>", None))
        self.algorithm_threshold_button.setText(_translate("DockClass", "W", None))
        self.label_20.setText(_translate("DockClass", "Use", None))
        self.macroclass_checkBox.setToolTip(_translate("DockClass", "<html><head/><body><p>Use the ID of macroclasses for the classification</p></body></html>", None))
        self.macroclass_checkBox.setText(_translate("DockClass", "MC ID", None))
        self.class_checkBox.setToolTip(_translate("DockClass", "<html><head/><body><p>Use the ID of classes for the classification</p></body></html>", None))
        self.class_checkBox.setText(_translate("DockClass", "C ID", None))
        self.algorithm_weight_button.setToolTip(_translate("DockClass", "<html><head/><body><p>Open tab Algorithm band weight</p></body></html>", None))
        self.algorithm_weight_button.setText(_translate("DockClass", "W", None))
        self.label_43.setText(_translate("DockClass", " Algorithm", None))
        self.label_21.setText(_translate("DockClass", "Use", None))
        self.LC_signature_checkBox.setToolTip(_translate("DockClass", "<html><head/><body><p>If checked, the Land Cover Signature Classification is used</p></body></html>", None))
        self.LC_signature_checkBox.setText(_translate("DockClass", "LCS", None))
        self.LCS_class_algorithm_checkBox.setToolTip(_translate("DockClass", "<html><head/><body><p>If checked, the selected Algorithm is used for unclassified pixels of the Land Cover Signature Classification</p></body></html>", None))
        self.LCS_class_algorithm_checkBox.setText(_translate("DockClass", "Algorithm", None))
        self.LCS_leave_unclassified_checkBox.setToolTip(_translate("DockClass", "<html><head/><body><p>If checked, the selected Algorithm is used only for class overlapping pixels of the Land Cover Signature Classification</p></body></html>", None))
        self.LCS_leave_unclassified_checkBox.setText(_translate("DockClass", "only overlap", None))
        self.LC_signature_button.setToolTip(_translate("DockClass", "<html><head/><body><p>Open tab LCS threshold</p></body></html>", None))
        self.label_46.setText(_translate("DockClass", " Land Cover Signature Classification", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("DockClass", " Classification algorithm", None))
        self.mask_checkBox.setToolTip(_translate("DockClass", "<html><head/><body><p>Select an optional mask vector</p></body></html>", None))
        self.mask_checkBox.setText(_translate("DockClass", "Apply mask", None))
        self.mask_lineEdit.setToolTip(_translate("DockClass", "<html><head/><body><p>Path of the optional mask shapefile</p></body></html>", None))
        self.resetMaskButton.setToolTip(_translate("DockClass", "<html><head/><body><p><span >Reset</span></p></body></html>", None))
        self.resetMaskButton.setText(_translate("DockClass", "Import library", None))
        self.vector_output_checkBox.setToolTip(_translate("DockClass", "<html><head/><body><p>Create a classification shapefile after the classification process</p></body></html>", None))
        self.vector_output_checkBox.setText(_translate("DockClass", "Create vector", None))
        self.report_checkBox.setToolTip(_translate("DockClass", "<html><head/><body><p>Calculate a classification report</p></body></html>", None))
        self.report_checkBox.setText(_translate("DockClass", "Classification report", None))
        self.alg_files_checkBox.setToolTip(_translate("DockClass", "<html><head/><body><p>If enabled, the rasters calculated by the classification algorithm (one per signature) are saved along with the classification</p></body></html>", None))
        self.alg_files_checkBox.setText(_translate("DockClass", "Save algorithm files", None))
        self.button_classification.setToolTip(_translate("DockClass", "<html><head/><body><p><span >Run</span></p></body></html>", None))
        self.button_classification.setText(_translate("DockClass", "Import library", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("DockClass", " Classification output", None))
        self.SCP_toolBox.setItemText(self.SCP_toolBox.indexOf(self.page_7), _translate("DockClass", "Classification dock", None))

import resources_rc
